<?php
require __DIR__ . '/SCTE35Parser.php';

$me = new SCTE35Parser();

$base64 = '';

//$arBase64 = array();
if (isset($_POST['base64']) && !empty($_POST['base64'])) {
	$base64 = $_POST['base64'];
}
$arBase64 = explode("\n", $base64);
$error = array();
$json = array();
$done = array();
if (!empty($base64)) {
	foreach ($arBase64 as $b64) {
		if (in_array($b64, $done)) continue;
		$done[] = $b64;
		try {
			$json[$b64] = $me->parseFromBase64($b64);
		}
		catch (Exception $e) {
			$error[$b64] = $e->getMessage();
		}
	}
}
?><html>
<head>
<title>SCTE35 Decoder</title>
<style type="text/css">
div {font-size:0.8em;font-family: sans-serif;}
.rel {position:relative;}
.abs {position:absolute;}
#time {top:-2em;}
#descTitle { height:5em; width:10em;}
#desc { height:4em; }
.x02 { background:#FEE; }
.x10 { background:#A5A; }
.x11 { background:#A5A; }
.x22 { background:#A55; }
.x23 { background:#A55; }
.x30 { background:#55A; }
.x31 { background:#55A; }
.x34 { background:#5A5; }
.x35 { background:#5A5; }
.dupl { background:#FFF; }
</style>
</head>
<body>
<form name="scte" method="POST">
Enter Base64 message(s) : <br/>
(one per line, they will be de-duplicated if necessary)<br/>
<textarea name="base64" cols=200 rows=5><?php echo $base64;?></textarea>
<br/>
<br/>
<input type="submit">
</form>
<br/>
<form method="post">
	<input type="hidden" name="base64" value="/DBoAAAAAAAAAP/wBQb/XpvxMABSAhRDVUVJIgACNX/AAAIGnBAAACIBAQIUQ1VFSQMABMl/wAAACD1gAAAwABMCJENVRUkAIAXcf8AAAgacEAwQQURGUgEzDQE0OxkF3AXDKAIAAPWpZLI=
/DCGAAAAAAAAAP/wBQb/XqQukABwAhxDVUVJNAAF3H/AAAH+XrAICAAAAAAAAAXcNAEBAhRDVUVJAwAESH/AAAAQesAAADABEwIkQ1VFSQAgBdx/wAACBpwQDBBBREZSATMNATQ7GQXcBcMoAgAAAhRDVUVJAwAEyX/AAAAAAAAAADEAE2X972E=
/DBoAAAAAAAAAP/wBQb/XrVSEABSAhRDVUVJAwAHJX/AAAAUmXAAADACEwIkQ1VFSQAgBdx/wAACBpwQDBBBREZSATMNATQ7GQXcBcMoAgAAAhRDVUVJAwAESH/AAAAAAAAAADEBE7k0EUs=
/DBoAAAAAAAAAP/wBQb/XsqUQABSAhRDVUVJAwAEmH/AAAANu6AAADADEwIkQ1VFSQAgBdx/wAACBpwQDBBBREZSATMNATQ7GQXcBcMoAgAAAhRDVUVJAwAHJX/AAAAAAAAAADECE2HnAeo=
/DBoAAAAAAAAAP/wBQb/Xtj4oABSAhRDVUVJAwAEzn/AAAAbd0AAADAEEwIkQ1VFSQAgBdx/wAACBpwQDBBBREZSATMNATQ7GQXcBcMoAgAAAhRDVUVJAwAEmH/AAAAAAAAAADEDE6azhrA=
/DBoAAAAAAAAAP/wBQb/XvUYoABSAhRDVUVJAwAG/X/AAAApMuAAADAFEwIkQ1VFSQAgBdx/wAACBpwQDBBBREZSATMNATQ7GQXcBcMoAgAAAhRDVUVJAwAEzn/AAAAAAAAAADEEE+M4eNg=
/DBoAAAAAAAAAP/wBQb/Xx70QABSAhRDVUVJAwAKq3/AAAAbd0AAADAGEwIkQ1VFSQAgBdx/wAACBpwQDBBBREZSATMNATQ7GQXcBcMoAgAAAhRDVUVJAwAG/X/AAAAAAAAAADEFE6s5ZWs=
/DBoAAAAAAAAAP/wBQb/XzsUQABSAhRDVUVJAwADQ3/AAAApMuAAADAHEwIkQ1VFSQAgBdx/wAACBpwQDBBBREZSATMNATQ7GQXcBcMoAgAAAhRDVUVJAwAKq3/AAAAAAAAAADEGE0lDqKw=
/DBoAAAAAAAAAP/wBQb/X2Tv4ABSAhRDVUVJAwAAv3/AAAApMuAAADAIEwIkQ1VFSQAgBdx/wAACBpwQDBBBREZSATMNATQ7GQXcBcMoAgAAAhRDVUVJAwADQ3/AAAAAAAAAADEHE3RHlDw=
/DBoAAAAAAAAAP/wBQb/X47LgABSAhRDVUVJAwABlH/AAAAbd0AAADAJEwIkQ1VFSQAgBdx/wAACBpwQDBBBREZSATMNATQ7GQXcBcMoAgAAAhRDVUVJAwAAv3/AAAAAAAAAADEIE96ZE9A=
/DBoAAAAAAAAAP/wBQb/X6rrgABSAhRDVUVJAwAByH/AAAAbd0AAADAKEwIkQ1VFSQAgBdx/wAACBpwQDBBBREZSATMNATQ7GQXcBcMoAgAAAhRDVUVJAwABlH/AAAAAAAAAADEJE6jhMWo=
/DBoAAAAAAAAAP/wBQb/X8cLgABSAhRDVUVJAwAJ/3/AAAAbd0AAADALEwIkQ1VFSQAgBdx/wAACBpwQDBBBREZSATMNATQ7GQXcBcMoAgAAAhRDVUVJAwAByH/AAAAAAAAAADEKE3cHOjw=
/DBoAAAAAAAAAP/wBQb/X+MrgABSAhRDVUVJAwADRX/AAAAUmXAAADAMEwIkQ1VFSQAgBdx/wAACBpwQDBBBREZSATMNATQ7GQXcBcMoAgAAAhRDVUVJAwAJ/3/AAAAAAAAAADELE/aoDE0=
/DBoAAAAAAAAAP/wBQb/X/htsABSAhRDVUVJAwAED3/AAAAbd0AAADANEwIkQ1VFSQAgBdx/wAACBpwQDBBBREZSATMNATQ7GQXcBcMoAgAAAhRDVUVJAwADRX/AAAAAAAAAADEMEyMMLrw=
/DBoAAAAAAAAAP/wBQb/YBSNsABSAhRDVUVJAwAB23/AAAANu6AAADAOEwIkQ1VFSQAgBdx/wAACBpwQDBBBREZSATMNATQ7GQXcBcMoAgAAAhRDVUVJAwAED3/AAAAAAAAAADENExas1WY=
/DBoAAAAAAAAAP/wBQb/YCLyEABSAhRDVUVJAwADon/AAAAbd0AAADAPEwIkQ1VFSQAgBdx/wAACBpwQDBBBREZSATMNATQ7GQXcBcMoAgAAAhRDVUVJAwAB23/AAAAAAAAAADEOEwiRrSU=
/DBoAAAAAAAAAP/wBQb/YD8SEABSAhRDVUVJAwAKXn/AAAAUmXAAADAQEwIkQ1VFSQAgBdx/wAACBpwQDBBBREZSATMNATQ7GQXcBcMoAgAAAhRDVUVJAwADon/AAAAAAAAAADEPE6/L/kM=
/DBoAAAAAAAAAP/wBQb/YFRUQABSAhRDVUVJAwAGn3/AAAANu6AAADAREwIkQ1VFSQAgBdx/wAACBpwQDBBBREZSATMNATQ7GQXcBcMoAgAAAhRDVUVJAwAKXn/AAAAAAAAAADEQE0btwNI=
/DBoAAAAAAAAAP/wBQb/YGK4oABSAhRDVUVJAwAE7n/AAAAbd0AAADASEwIkQ1VFSQAgBdx/wAACBpwQDBBBREZSATMNATQ7GQXcBcMoAgAAAhRDVUVJAwAGn3/AAAAAAAAAADERE2SYt0w=
/DBoAAAAAAAAAP/wBQb/YH7YoABSAhRDVUVJAwAFAn/AAAAbd0AAADATEwIkQ1VFSQAgBdx/wAACBpwQDBBBREZSATMNATQ7GQXcBcMoAgAAAhRDVUVJAwAE7n/AAAAAAAAAADESE3h3XBo=
/DBCAAAAAAAAAP/wBQb/YJpP4AAsAhRDVUVJAwABl3/AAAAIPWAAADAAAAIUQ1VFSQMABQJ/wAAAAAAAAAAxExO+SYPC
/DBgAAAAAAAAAP/wBQb/YKKNQABKAhxDVUVJNAAF3H/AAAAAAAAICAAAAAAAAAXcNQEBAhRDVUVJIgACNX/AAAAAAAAAACMBAQIUQ1VFSQMAAZd/wAAAAAAAAAAxAAAq1sHb
/DA8AAAAAAAAAP/wBQb/YovWHwAmAiRDVUVJACAF+n/AAAIJBtAMEEFERlIBMw0BNDsZBfoFyggCAABoBCnj
/DBoAAAAAAAAAP/wBQb/Z1+8IABSAhRDVUVJIgAH4n/AAAIJBtAAACIBAQIUQ1VFSQMAAZ5/wAAACD1gAAAwABACJENVRUkAIAX6f8AAAgkG0AwQQURGUgEzDQE0OxkF+gXKCAIAAAeTzLk=
/DCGAAAAAAAAAP/wBQb/Z2f5gABwAhxDVUVJNAAF+n/AAAIAyXAICAAAAAAAAAX6NAEBAhRDVUVJAwAK7H/AAAAbd0AAADABEAIkQ1VFSQAgBfp/wAACCQbQDBBBREZSATMNATQ7GQX6BcoIAgAAAhRDVUVJAwABnn/AAAAAAAAAADEAEFk6yps=
/DBoAAAAAAAAAP/wBQb/Z4QZgABSAhRDVUVJAwACXX/AAAApMuAAADACEAIkQ1VFSQAgBfp/wAACCQbQDBBBREZSATMNATQ7GQX6BcoIAgAAAhRDVUVJAwAK7H/AAAAAAAAAADEBELRi8ZI=
/DBoAAAAAAAAAP/wBQb/Z631IABSAhRDVUVJAwAFmn/AAAAbd0AAADADEAIkQ1VFSQAgBfp/wAACCQbQDBBBREZSATMNATQ7GQX6BcoIAgAAAhRDVUVJAwACXX/AAAAAAAAAADECEKAHxuY=
/DBoAAAAAAAAAP/wBQb/Z8oVIABSAhRDVUVJAwAEwX/AAAAbd0AAADAEEAIkQ1VFSQAgBfp/wAACCQbQDBBBREZSATMNATQ7GQX6BcoIAgAAAhRDVUVJAwAFmn/AAAAAAAAAADEDEJLLTHc=
/DBoAAAAAAAAAP/wBQb/Z+Y1IABSAhRDVUVJAwACFX/AAAApMuAAADAFEAIkQ1VFSQAgBfp/wAACCQbQDBBBREZSATMNATQ7GQX6BcoIAgAAAhRDVUVJAwAEwX/AAAAAAAAAADEEEHr08nI=
/DBoAAAAAAAAAP/wBQb/aBAQwABSAhRDVUVJAwAHFX/AAAApMuAAADAGEAIkQ1VFSQAgBfp/wAACCQbQDBBBREZSATMNATQ7GQX6BcoIAgAAAhRDVUVJAwACFX/AAAAAAAAAADEFEBvbgTQ=
/DBoAAAAAAAAAP/wBQb/aDnsYABSAhRDVUVJAwAK7X/AAAANu6AAADAHEAIkQ1VFSQAgBfp/wAACCQbQDBBBREZSATMNATQ7GQX6BcoIAgAAAhRDVUVJAwAHFX/AAAAAAAAAADEGECzY/JQ=
/DBoAAAAAAAAAP/wBQb/aEhQwABSAhRDVUVJAwACfn/AAAAbd0AAADAIEAIkQ1VFSQAgBfp/wAACCQbQDBBBREZSATMNATQ7GQX6BcoIAgAAAhRDVUVJAwAK7X/AAAAAAAAAADEHEJlhvEQ=
/DBoAAAAAAAAAP/wBQb/aGRwwABSAhRDVUVJAwAC/X/AAAApMuAAADAJEAIkQ1VFSQAgBfp/wAACCQbQDBBBREZSATMNATQ7GQX6BcoIAgAAAhRDVUVJAwACfn/AAAAAAAAAADEIEMD+l0g=
/DBoAAAAAAAAAP/wBQb/aI5MYABSAhRDVUVJAwAGo3/AAAAQesAAADAKEAIkQ1VFSQAgBfp/wAACCQbQDBBBREZSATMNATQ7GQX6BcoIAgAAAhRDVUVJAwAC/X/AAAAAAAAAADEJEEpAdDY=
/DBoAAAAAAAAAP/wBQb/aJ9v4ABSAhRDVUVJAwAFtn/AAAApMuAAADALEAIkQ1VFSQAgBfp/wAACCQbQDBBBREZSATMNATQ7GQX6BcoIAgAAAhRDVUVJAwAGo3/AAAAAAAAAADEKEFY3yNU=
/DBoAAAAAAAAAP/wBQb/aMlLgABSAhRDVUVJAwAEhX/AAAAYuCAAADAMEAIkQ1VFSQAgBfp/wAACCQbQDBBBREZSATMNATQ7GQX6BcoIAgAAAhRDVUVJAwAFtn/AAAAAAAAAADELEDZl/Fc=
/DBoAAAAAAAAAP/wBQb/aOKsYABSAhRDVUVJAwAFT3/AAAANu6AAADANEAIkQ1VFSQAgBfp/wAACCQbQDBBBREZSATMNATQ7GQX6BcoIAgAAAhRDVUVJAwAEhX/AAAAAAAAAADEMEJymqZQ=
/DBoAAAAAAAAAP/wBQb/aPEQwABSAhRDVUVJAwALUX/AAAAbd0AAADAOEAIkQ1VFSQAgBfp/wAACCQbQDBBBREZSATMNATQ7GQX6BcoIAgAAAhRDVUVJAwAFT3/AAAAAAAAAADENELJj4No=
/DBoAAAAAAAAAP/wBQb/aQ0wwABSAhRDVUVJAwAGrH/AAAApMuAAADAPEAIkQ1VFSQAgBfp/wAACCQbQDBBBREZSATMNATQ7GQX6BcoIAgAAAhRDVUVJAwALUX/AAAAAAAAAADEOEMyQtWQ=
/DBoAAAAAAAAAP/wBQb/aTcMYABSAhRDVUVJAwADdX/AAAApMuAAADAQEAIkQ1VFSQAgBfp/wAACCQbQDBBBREZSATMNATQ7GQX6BcoIAgAAAhRDVUVJAwAGrH/AAAAAAAAAADEPEFFqGxQ=
/DBCAAAAAAAAAP/wBQb/aWA/QAAsAhRDVUVJAwAHY3/AAAAIg7AAADAAAAIUQ1VFSQMAA3V/wAAAAAAAAAAxEBDPgzkA
/DBgAAAAAAAAAP/wBQb/aWjC8ABKAhxDVUVJNAAF+n/AAAAAAAAICAAAAAAAAAX6NQEBAhRDVUVJIgAH4n/AAAAAAAAAACMBAQIUQ1VFSQMAB2N/wAAAAAAAAAAxAAD4w+YX
/DA8AAAAAAAAAP/wBQb/b2rpLwAmAiRDVUVJACAGUn/AAAJS2tAMEEFERlIBMw0BNDsZBlIGnAgCAACvPcpZ" />
	<input type="submit" value="TimeSignal 0x02/Break/Placement/Ads" />
</form>
<form method="post">
	<input type="hidden" name="base64" value="/DA0AAAAAAAAAP/wBQb+ow3aQAAeAhxDVUVJEAAEVH/AAAAAAAAICAAAAAAAAPGoEQAAMMH2bA==
/DA0AAAAAAAAAP/wBQb+o00UMAAeAhxDVUVJEAALVH/AABDHw6AICAAAAAAAAPG4EAAArNYHYA==
/DA8AAAAAAAAAP/wBQb+pVQGzwAmAiRDVUVJACAFRn/AAAIKEgAMEEFERlIBMw0BNDscBUYFzQACAAAaIkcQ
/DBoAAAAAAAAAP/wBQb+qifs0ABSAhRDVUVJIgAHsH/AAAIKEgAAACIBAQIUQ1VFSQMACJR/wAAACD1gAAAwABICJENVRUkAIAVGf8AAAgoSAAwQQURGUgEzDQE0OxwFRgXNAAIAAP05AiA=
/DCGAAAAAAAAAP/wBQb+qjAqMABwAhxDVUVJNAAFRn/AAAIB1KAICAAAAAAAAAVGNAEBAhRDVUVJAwAEXn/AAAAUmXAAADABEgIkQ1VFSQAgBUZ/wAACChIADBBBREZSATMNATQ7HAVGBc0AAgAAAhRDVUVJAwAIlH/AAAAAAAAAADEAEi3YN8k=
/DBoAAAAAAAAAP/wBQb+qkVsYABSAhRDVUVJAwAHHX/AAAApMuAAADACEgIkQ1VFSQAgBUZ/wAACChIADBBBREZSATMNATQ7HAVGBc0AAgAAAhRDVUVJAwAEXn/AAAAAAAAAADEBElPtsoo=
/DBoAAAAAAAAAP/wBQb+qm9IAABSAhRDVUVJAwAFMX/AAAApMuAAADADEgIkQ1VFSQAgBUZ/wAACChIADBBBREZSATMNATQ7HAVGBc0AAgAAAhRDVUVJAwAHHX/AAAAAAAAAADECEvd0yIA=
/DBoAAAAAAAAAP/wBQb+qpkjoABSAhRDVUVJAwAFs3/AAAApMuAAADAEEgIkQ1VFSQAgBUZ/wAACChIADBBBREZSATMNATQ7HAVGBc0AAgAAAhRDVUVJAwAFMX/AAAAAAAAAADEDEoqXX8c=
/DBoAAAAAAAAAP/wBQb+qsL/QABSAhRDVUVJAwALYH/AAAANu6AAADAFEgIkQ1VFSQAgBUZ/wAACChIADBBBREZSATMNATQ7HAVGBc0AAgAAAhRDVUVJAwAFs3/AAAAAAAAAADEEEri4cI4=
/DBoAAAAAAAAAP/wBQb+qtFjoABSAhRDVUVJAwAFkH/AAAApMuAAADAGEgIkQ1VFSQAgBUZ/wAACChIADBBBREZSATMNATQ7HAVGBc0AAgAAAhRDVUVJAwALYH/AAAAAAAAAADEFElh4j2s=
/DBoAAAAAAAAAP/wBQb+qvs/QABSAhRDVUVJAwAC8H/AAAAQesAAADAHEgIkQ1VFSQAgBUZ/wAACChIADBBBREZSATMNATQ7HAVGBc0AAgAAAhRDVUVJAwAFkH/AAAAAAAAAADEGErRYYD0=
/DBoAAAAAAAAAP/wBQb+qwxiwABSAhRDVUVJAwAAx3/AAAAbd0AAADAIEgIkQ1VFSQAgBUZ/wAACChIADBBBREZSATMNATQ7HAVGBc0AAgAAAhRDVUVJAwAC8H/AAAAAAAAAADEHEnuvWrk=
/DBoAAAAAAAAAP/wBQb+qyiCwABSAhRDVUVJAwAKHX/AAAANu6AAADAJEgIkQ1VFSQAgBUZ/wAACChIADBBBREZSATMNATQ7HAVGBc0AAgAAAhRDVUVJAwAAx3/AAAAAAAAAADEIEpn/uTA=
/DBoAAAAAAAAAP/wBQb+qzbnIABSAhRDVUVJAwAFhH/AAAAbd0AAADAKEgIkQ1VFSQAgBUZ/wAACChIADBBBREZSATMNATQ7HAVGBc0AAgAAAhRDVUVJAwAKHX/AAAAAAAAAADEJElI+yuc=
/DBoAAAAAAAAAP/wBQb+q1MHIABSAhRDVUVJAwAE5n/AAAANu6AAADALEgIkQ1VFSQAgBUZ/wAACChIADBBBREZSATMNATQ7HAVGBc0AAgAAAhRDVUVJAwAFhH/AAAAAAAAAADEKEmrPxHs=
/DBoAAAAAAAAAP/wBQb+q2FrgABSAhRDVUVJAwALcH/AAAApMuAAADAMEgIkQ1VFSQAgBUZ/wAACChIADBBBREZSATMNATQ7HAVGBc0AAgAAAhRDVUVJAwAE5n/AAAAAAAAAADELEo68ogo=
/DBoAAAAAAAAAP/wBQb+q4tHIABSAhRDVUVJAwAFwX/AAAAbd0AAADANEgIkQ1VFSQAgBUZ/wAACChIADBBBREZSATMNATQ7HAVGBc0AAgAAAhRDVUVJAwALcH/AAAAAAAAAADEMEpuDAzs=
/DBoAAAAAAAAAP/wBQb+q6dnIABSAhRDVUVJAwACR3/AAAApMuAAADAOEgIkQ1VFSQAgBUZ/wAACChIADBBBREZSATMNATQ7HAVGBc0AAgAAAhRDVUVJAwAFwX/AAAAAAAAAADENEsvomew=
/DBoAAAAAAAAAP/wBQb+q9FCwABSAhRDVUVJAwAGDn/AAAANu6AAADAPEgIkQ1VFSQAgBUZ/wAACChIADBBBREZSATMNATQ7HAVGBc0AAgAAAhRDVUVJAwACR3/AAAAAAAAAADEOEqhWIKQ=
/DBoAAAAAAAAAP/wBQb+q9+nIABSAhRDVUVJAwAIuX/AAAApMuAAADAQEgIkQ1VFSQAgBUZ/wAACChIADBBBREZSATMNATQ7HAVGBc0AAgAAAhRDVUVJAwAGDn/AAAAAAAAAADEPEiOC2C0=
/DBoAAAAAAAAAP/wBQb+rAmCwABSAhRDVUVJAwAGHn/AAAAXWJAAADAREgIkQ1VFSQAgBUZ/wAACChIADBBBREZSATMNATQ7HAVGBc0AAgAAAhRDVUVJAwAIuX/AAAAAAAAAADEQEjW1aqw=
/DBoAAAAAAAAAP/wBQb+rCGEEABSAhRDVUVJAwADY3/AAAAIPWAAADASEgIkQ1VFSQAgBUZ/wAACChIADBBBREZSATMNATQ7HAVGBc0AAgAAAhRDVUVJAwAGHn/AAAAAAAAAADEREqtsQto=
/DBCAAAAAAAAAP/wBQb+rCnBcAAsAhRDVUVJAwAJW3/AAAAIPWAAADAAAAIUQ1VFSQMAA2N/wAAAAAAAAAAxEhLiCHqs
/DBgAAAAAAAAAP/wBQb+rDH+0ABKAhxDVUVJNAAFRn/AAAAAAAAICAAAAAAAAAVGNQEBAhRDVUVJIgAHsH/AAAAAAAAAACMBAQIUQ1VFSQMACVt/wAAAAAAAAAAxAAC88SGM
/DA0AAAAAAAAAP/wBQb+tBTJwAAeAhxDVUVJEAALVH/AAAAAAAAICAAAAAAAAPG4EQAAVcm4Kg==
/DA0AAAAAAAAAP/wBQb+tF8AMAAeAhxDVUVJEAADAH/AABLRVxAICAAAAAAAAPHnEAAAN8RDlw==
/DA8AAAAAAAAAP/wBQb+thQLnwAmAiRDVUVJACAFjH/AAAIKEgAMEEFERlIBMw0BNDscBYwFzQACAACv0ueh
/DBoAAAAAAAAAP/wBQb+uufxoABSAhRDVUVJIgACuX/AAAIKEgAAACIBAQIUQ1VFSQMAArB/wAAACD1gAAAwABICJENVRUkAIAWMf8AAAgoSAAwQQURGUgEzDQE0OxwFjAXNAAIAALjsoF8=
/DCGAAAAAAAAAP/wBQb+uvAvAABwAhxDVUVJNAAFjH/AAAIB1KAICAAAAAAAAAWMNAEBAhRDVUVJAwAEs3/AAAAbd0AAADABEgIkQ1VFSQAgBYx/wAACChIADBBBREZSATMNATQ7HAWMBc0AAgAAAhRDVUVJAwACsH/AAAAAAAAAADEAEpHHjIA=
/DBoAAAAAAAAAP/wBQb+uwxPAABSAhRDVUVJAwAKe3/AAAApMuAAADACEgIkQ1VFSQAgBYx/wAACChIADBBBREZSATMNATQ7HAWMBc0AAgAAAhRDVUVJAwAEs3/AAAAAAAAAADEBEu9Qds8=
/DBoAAAAAAAAAP/wBQb+uzYqoABSAhRDVUVJAwALSH/AAAAXWJAAADADEgIkQ1VFSQAgBYx/wAACChIADBBBREZSATMNATQ7HAWMBc0AAgAAAhRDVUVJAwAKe3/AAAAAAAAAADECEoDk15c=
/DBoAAAAAAAAAP/wBQb+u04r8ABSAhRDVUVJAwAGnH/AAAAg9YAAADAEEgIkQ1VFSQAgBYx/wAACChIADBBBREZSATMNATQ7HAWMBc0AAgAAAhRDVUVJAwALSH/AAAAAAAAAADEDEoZ6ySo=
/DBoAAAAAAAAAP/wBQb+u2/KMABSAhRDVUVJAwAAMn/AAAApMuAAADAFEgIkQ1VFSQAgBYx/wAACChIADBBBREZSATMNATQ7HAWMBc0AAgAAAhRDVUVJAwAGnH/AAAAAAAAAADEEEt04GR0=
/DBoAAAAAAAAAP/wBQb+u5ml0ABSAhRDVUVJAwADBX/AAAAbd0AAADAGEgIkQ1VFSQAgBYx/wAACChIADBBBREZSATMNATQ7HAWMBc0AAgAAAhRDVUVJAwAAMn/AAAAAAAAAADEFEgcFZds=
/DBoAAAAAAAAAP/wBQb+u7XF0ABSAhRDVUVJAwAIW3/AAAAbd0AAADAHEgIkQ1VFSQAgBYx/wAACChIADBBBREZSATMNATQ7HAWMBc0AAgAAAhRDVUVJAwADBX/AAAAAAAAAADEGEqdGTg8=
/DBoAAAAAAAAAP/wBQb+u9Hl0ABSAhRDVUVJAwAFyX/AAAANu6AAADAIEgIkQ1VFSQAgBYx/wAACChIADBBBREZSATMNATQ7HAWMBc0AAgAAAhRDVUVJAwAIW3/AAAAAAAAAADEHEkmvozg=
/DBoAAAAAAAAAP/wBQb+u+BKMABSAhRDVUVJAwAAzn/AAAApMuAAADAJEgIkQ1VFSQAgBYx/wAACChIADBBBREZSATMNATQ7HAWMBc0AAgAAAhRDVUVJAwAFyX/AAAAAAAAAADEIEtZJlvY=
/DBoAAAAAAAAAP/wBQb+vAol0ABSAhRDVUVJAwAKwn/AAAAbd0AAADAKEgIkQ1VFSQAgBYx/wAACChIADBBBREZSATMNATQ7HAWMBc0AAgAAAhRDVUVJAwAAzn/AAAAAAAAAADEJEu+Ecp8=
/DBoAAAAAAAAAP/wBQb+vCZF0ABSAhRDVUVJAwAHtn/AAAAiVRAAADALEgIkQ1VFSQAgBYx/wAACChIADBBBREZSATMNATQ7HAWMBc0AAgAAAhRDVUVJAwAKwn/AAAAAAAAAADEKEmIrHj4=
/DBoAAAAAAAAAP/wBQb+vElDoABSAhRDVUVJAwAHEX/AAAAQesAAADAMEgIkQ1VFSQAgBYx/wAACChIADBBBREZSATMNATQ7HAWMBc0AAgAAAhRDVUVJAwAHtn/AAAAAAAAAADELEkxCclE=
/DBoAAAAAAAAAP/wBQb+vFpnIABSAhRDVUVJAwALGH/AAAAbd0AAADANEgIkQ1VFSQAgBYx/wAACChIADBBBREZSATMNATQ7HAWMBc0AAgAAAhRDVUVJAwAHEX/AAAAAAAAAADEMEk4bUF4=
/DBoAAAAAAAAAP/wBQb+vHaHIABSAhRDVUVJAwAIbX/AAAAUmXAAADAOEgIkQ1VFSQAgBYx/wAACChIADBBBREZSATMNATQ7HAWMBc0AAgAAAhRDVUVJAwALGH/AAAAAAAAAADENEkEHGk8=
/DBoAAAAAAAAAP/wBQb+vIvJUABSAhRDVUVJAwAGa3/AAAAbd0AAADAPEgIkQ1VFSQAgBYx/wAACChIADBBBREZSATMNATQ7HAWMBc0AAgAAAhRDVUVJAwAIbX/AAAAAAAAAADEOEmIXzbk=
/DBoAAAAAAAAAP/wBQb+vKfpUABSAhRDVUVJAwABeX/AAAAQesAAADAQEgIkQ1VFSQAgBYx/wAACChIADBBBREZSATMNATQ7HAWMBc0AAgAAAhRDVUVJAwAGa3/AAAAAAAAAADEPEugCqog=
/DBoAAAAAAAAAP/wBQb+vLkM0ABSAhRDVUVJAwAKnH/AAAAbd0AAADAREgIkQ1VFSQAgBYx/wAACChIADBBBREZSATMNATQ7HAWMBc0AAgAAAhRDVUVJAwABeX/AAAAAAAAAADEQEuf65so=
/DBoAAAAAAAAAP/wBQb+vNUs0ABSAhRDVUVJAwAJxH/AAAAUmXAAADASEgIkQ1VFSQAgBYx/wAACChIADBBBREZSATMNATQ7HAWMBc0AAgAAAhRDVUVJAwAKnH/AAAAAAAAAADEREm5QJAc=
/DBCAAAAAAAAAP/wBQb+vOnGQAAsAhRDVUVJAwAJJX/AAAAIPWAAADAAAAIUQ1VFSQMACcR/wAAAAAAAAAAxEhI4gwhz
/DBgAAAAAAAAAP/wBQb+vPIDoABKAhxDVUVJNAAFjH/AAAAAAAAICAAAAAAAAAWMNQEBAhRDVUVJIgACuX/AAAAAAAAAACMBAQIUQ1VFSQMACSV/wAAAAAAAAAAxAACJPGrg
/DA8AAAAAAAAAP/wBQb+vxWGvwAmAiRDVUVJACAFoH/AAAIJWzAMEEFERlIBMw0BNDscBaAFyvgCAAAjFqC7
/DBoAAAAAAAAAP/wBQb+w+l60ABSAhRDVUVJIgAEkX/AAAIJWzAAACIBAQIUQ1VFSQMAADN/wAAACD1gAAAwABMCJENVRUkAIAWgf8AAAglbMAwQQURGUgEzDQE0OxwFoAXK+AIAAMWw7UU=
/DCGAAAAAAAAAP/wBQb+w/G4MABwAhxDVUVJNAAFoH/AAAIBHdAICAAAAAAAAAWgNAEBAhRDVUVJAwAA6n/AAAAUmXAAADABEwIkQ1VFSQAgBaB/wAACCVswDBBBREZSATMNATQ7HAWgBcr4AgAAAhRDVUVJAwAAM3/AAAAAAAAAADEAE8fT3B8=
/DBoAAAAAAAAAP/wBQb+xAb6YABSAhRDVUVJAwAKpX/AAAAbd0AAADACEwIkQ1VFSQAgBaB/wAACCVswDBBBREZSATMNATQ7HAWgBcr4AgAAAhRDVUVJAwAA6n/AAAAAAAAAADEBE/S/9tU=
/DBoAAAAAAAAAP/wBQb+xCMaYABSAhRDVUVJAwABCn/AAAANu6AAADADEwIkQ1VFSQAgBaB/wAACCVswDBBBREZSATMNATQ7HAWgBcr4AgAAAhRDVUVJAwAKpX/AAAAAAAAAADECEyXYh1s=
/DBoAAAAAAAAAP/wBQb+xDF+wABSAhRDVUVJAwABw3/AAAAUmXAAADAEEwIkQ1VFSQAgBaB/wAACCVswDBBBREZSATMNATQ7HAWgBcr4AgAAAhRDVUVJAwABCn/AAAAAAAAAADEDEyvGEag=
/DBoAAAAAAAAAP/wBQb+xEbA8ABSAhRDVUVJAwAEdn/AAAAbd0AAADAFEwIkQ1VFSQAgBaB/wAACCVswDBBBREZSATMNATQ7HAWgBcr4AgAAAhRDVUVJAwABw3/AAAAAAAAAADEEE8M4RtE=
/DBoAAAAAAAAAP/wBQb+xGLg8ABSAhRDVUVJAwADqX/AAAANu6AAADAGEwIkQ1VFSQAgBaB/wAACCVswDBBBREZSATMNATQ7HAWgBcr4AgAAAhRDVUVJAwAEdn/AAAAAAAAAADEFE4FhJyo=
/DBoAAAAAAAAAP/wBQb+xHFFUABSAhRDVUVJAwAA6n/AAAAUmXAAADAHEwIkQ1VFSQAgBaB/wAACCVswDBBBREZSATMNATQ7HAWgBcr4AgAAAhRDVUVJAwADqX/AAAAAAAAAADEGEziDDNM=
/DBoAAAAAAAAAP/wBQb+xIaHgABSAhRDVUVJAwAIBn/AAAAbd0AAADAIEwIkQ1VFSQAgBaB/wAACCVswDBBBREZSATMNATQ7HAWgBcr4AgAAAhRDVUVJAwAA6n/AAAAAAAAAADEHE/L5364=
/DBoAAAAAAAAAP/wBQb+xKKngABSAhRDVUVJAwAHhn/AAAApMuAAADAJEwIkQ1VFSQAgBaB/wAACCVswDBBBREZSATMNATQ7HAWgBcr4AgAAAhRDVUVJAwAIBn/AAAAAAAAAADEIE11e1+E=
/DBoAAAAAAAAAP/wBQb+xMyDIABSAhRDVUVJAwAC1X/AAAAYuCAAADAKEwIkQ1VFSQAgBaB/wAACCVswDBBBREZSATMNATQ7HAWgBcr4AgAAAhRDVUVJAwAHhn/AAAAAAAAAADEJE0x6RR8=
/DBoAAAAAAAAAP/wBQb+xOXkAABSAhRDVUVJAwAFZH/AAAAUmXAAADALEwIkQ1VFSQAgBaB/wAACCVswDBBBREZSATMNATQ7HAWgBcr4AgAAAhRDVUVJAwAC1X/AAAAAAAAAADEKE4A1zgI=
/DBoAAAAAAAAAP/wBQb+xPsmMABSAhRDVUVJAwAGFn/AAAApMuAAADAMEwIkQ1VFSQAgBaB/wAACCVswDBBBREZSATMNATQ7HAWgBcr4AgAAAhRDVUVJAwAFZH/AAAAAAAAAADELE97z1zQ=
/DBoAAAAAAAAAP/wBQb+xSUB0ABSAhRDVUVJAwAKjH/AAAAbd0AAADANEwIkQ1VFSQAgBaB/wAACCVswDBBBREZSATMNATQ7HAWgBcr4AgAAAhRDVUVJAwAGFn/AAAAAAAAAADEMExxnzjY=
/DBoAAAAAAAAAP/wBQb+xUEh0ABSAhRDVUVJAwALmX/AAAAUmXAAADAOEwIkQ1VFSQAgBaB/wAACCVswDBBBREZSATMNATQ7HAWgBcr4AgAAAhRDVUVJAwAKjH/AAAAAAAAAADENEwMfnhs=
/DBoAAAAAAAAAP/wBQb+xVZkAABSAhRDVUVJAwAHT3/AAAAR2lAAADAPEwIkQ1VFSQAgBaB/wAACCVswDBBBREZSATMNATQ7HAWgBcr4AgAAAhRDVUVJAwALmX/AAAAAAAAAADEOE6ZWu5w=
/DBoAAAAAAAAAP/wBQb+xWj1IABSAhRDVUVJAwACsX/AAAAflfAAADAQEwIkQ1VFSQAgBaB/wAACCVswDBBBREZSATMNATQ7HAWgBcr4AgAAAhRDVUVJAwAHT3/AAAAAAAAAADEPE6WJJP8=
/DBoAAAAAAAAAP/wBQb+xYklwABSAhRDVUVJAwAK5n/AAAAbd0AAADAREwIkQ1VFSQAgBaB/wAACCVswDBBBREZSATMNATQ7HAWgBcr4AgAAAhRDVUVJAwACsX/AAAAAAAAAADEQE0+0e2A=
/DBoAAAAAAAAAP/wBQb+xaVFwABSAhRDVUVJAwAE7X/AAAApMuAAADASEwIkQ1VFSQAgBaB/wAACCVswDBBBREZSATMNATQ7HAWgBcr4AgAAAhRDVUVJAwAK5n/AAAAAAAAAADERE0PU+zA=
/DBoAAAAAAAAAP/wBQb+xc8hYABSAhRDVUVJAwAGVH/AAAAbd0AAADATEwIkQ1VFSQAgBaB/wAACCVswDBBBREZSATMNATQ7HAWgBcr4AgAAAhRDVUVJAwAE7X/AAAAAAAAAADESE+no6H0=
/DBCAAAAAAAAAP/wBQb+xeqYoAAsAhRDVUVJAwABO3/AAAAIPWAAADAAAAIUQ1VFSQMABlR/wAAAAAAAAAAxExNcTkpe
/DBgAAAAAAAAAP/wBQb+xfLWAABKAhxDVUVJNAAFoH/AAAAAAAAICAAAAAAAAAWgNQEBAhRDVUVJIgAEkX/AAAAAAAAAACMBAQIUQ1VFSQMAATt/wAAAAAAAAAAxAAD0Wx69
/DA0AAAAAAAAAP/wBQb+xzA7IAAeAhxDVUVJEAADAH/AAAAAAAAICAAAAAAAAPHnEQAAtL0AdQ==
/DA0AAAAAAAAAP/wBQb+x3OTwAAeAhxDVUVJEAAF6X/AABKe98AICAAAAAAAAPH5EAAAs10N8Q==" />
	<input type="submit" value="TimeSignal Program and 0x02/Break/Placement/Ads" />
</form>
<?php

// Display Graphical Timeline
echo "<h1>Graphical Events Timeline</h1>\n";
$start = null;
$timeline = array();
$types = array();
$eventIds = array();
foreach ($json as $b64 => $dataJson) {
	$data = json_decode($dataJson);
	if ($start === null)
		$start = $data->splice_command->pts_time;
	foreach ($data->splice_descriptors as $descriptor) {
		$item = array(
			'start' => sprintf("%.03f", ($data->splice_command->pts_time - $start) / 90000),
			'duration' => $descriptor->segmentation_duration_text,
			'json' => json_encode($data, JSON_PRETTY_PRINT),
			'first' => (bool)(!in_array($descriptor->segmentation_event_id.$descriptor->segment_type_text, $eventIds))
		);
		$eventIds[] = $descriptor->segmentation_event_id.$descriptor->segment_type_text;
		if (preg_match("#\(0(x.*)\)#", $descriptor->segment_type_text, $m)) {
			$types[$m[1]] = $descriptor->segment_type_text;
		}
		$timeline[$m[1]][] = $item;
	}
}
echo '<div class="rel" style="height:'.(count($types)*5).'em;">';
$top = 0;
$max = 0;
$div = 10;
ksort($types);
foreach ($types as $type => $text) {
	echo '<div id="descTitle" class="abs '.$type.'" style="top:'.($top).'em;">'.$text.'</div>';
	foreach ($timeline[$type] as $desc) {
		if ($desc['first']) {
			echo '<div id="desc" class="abs '.$type.'" style="top:'.($top).'em; left:'.(10 + $desc['start']/$div).'em;width:'.max($desc['duration']/$div,0.2).'em;">'.$type.'</div>';
		}
		else {
			echo '<div id="desc" class="abs '.$type.' dupl" style="top:'.($top).'em; left:'.(10 + $desc['start']/$div).'em;width:'.max($desc['duration']/$div,0.2).'em;">'.$type.'</div>';	
		}
		$max = max($max,$desc['start']+$desc['duration']);
	}
	$top += 5;
}
for ($i=0; $i<=$max; $i+=300) {
	echo '<div id="time" class="abs" style="left:'.(10+$i/$div).'em;">+'.$i.' sec.</div>';
}
echo '</div>';

// Display Timeline
echo "<h1>Events Timeline</h1>\n";
$start = null;
echo "<pre>\n";
$pattern = "%-20s%-15s%-15s%-20s%-25s%-10s\n";
echo sprintf($pattern, "Time", "Program", "AdServer", "Break", "Placement Opportunity", "Advertisement");
echo sprintf($pattern, "----", "-------", "--------", "-----", "---------------------", "-------------");
foreach ($arBase64 as $b64) {
	if (!isset($json[$b64])) {
		if (isset($error[$b64]))
			echo "Error on ".$b64."\n";
		else
			echo "Not processed: ".$b64."\n";
	}
	else {
		//echo "OK: ".$b64."\n";
		$data = json_decode($json[$b64]);
		if ($start === null) {
			$start = $data->splice_command->pts_time;
		}
		$out = array("Time" => $data->splice_command->pts_time_text, "Program" => "", "AdServer" => "", "Break" => "", "Placement Opportunity" => "", "Advertisement" => "");
		$out["Time"] = sprintf("+%.03f sec", ($data->splice_command->pts_time - $start) / 90000);
		foreach ($data->splice_descriptors as $descriptor) {
			switch ($descriptor->segment_type_id) {
				case '02':
					$out['AdServer'] = $descriptor->segmentation_upid->code . ' ' . $descriptor->segmentation_duration_text;
					break;
				case '16':
					$out['Program'] .= ' +Start' . ' ' . $descriptor->segmentation_duration_text;
					break;
				case '17':
					$out['Program'] .= ' -End';
					break;
				case '34':
					$out['Break'] .= ' +Start' . ' ' . $descriptor->segmentation_duration_text;
					break;
				case '35':
					$out['Break'] .= ' -End';
					break;
				case '52':
					$out['Placement Opportunity'] .= ' +Start' . ' ' . $descriptor->segmentation_duration_text;
					break;
				case '53':
					$out['Placement Opportunity'] .= ' -End';
					break;
				case '48':
					$out['Advertisement'] .= ' +Start' . ' ' . $descriptor->segmentation_duration_text;
					break;
				case '49':
					$out['Advertisement'] = ' -End' . $out['Advertisement'];
					break;
			}
			//echo "\t";
			//echo $descriptor->segment_type_text;
		}
		echo sprintf($pattern, $out['Time'], $out['Program'], $out['AdServer'], $out['Break'], $out['Placement Opportunity'], $out['Advertisement']);
	}
}
echo "</pre>";

// Display Errors and JSON
echo "<h1>Messages details</h1>";
foreach ($done as $b64) { ?>
	<h3><?php echo $b64; ?></h3>
	<?php if (isset($error[$b64]) && !empty($error[$i])) {
		echo '<h4 class="error">'.$error[$b64].'</h4>';
	} ?>
	<?php if (isset($json[$b64]) && !empty($json[$b64])) { ?>
	<br/>
	<br/>
	JSON output :
	<pre>
	<?php echo json_encode(json_decode($json[$b64]), JSON_PRETTY_PRINT); ?>
	</pre>
<?php } ?>
<hr/>
<?php } ?>
<script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js"/></script>
<style>
.text { background: yellow; color: black; }
.id { background: orange; color: black; }
.type { background: lightgreen; color: black; }
.bold { font-weight: bold; }
.true { color: blue; }
.false { color: red; }
.error { color: red; font-size:2em; }
</style>
<script>
var context = document.querySelectorAll("pre");
var instance = new Mark(context);
instance.markRegExp(/[^\s]+_text.*/, {"element":"span","className":"text"});
instance.markRegExp(/[^\s]+segment_type_text.*/, {"element":"span","className":"type"});
instance.markRegExp(/[^\s]+segmentation_event_id_text.*/, {"element":"span","className":"id"});
instance.markRegExp(/"\(.*\) [^"]+"/,{"element":"span","className":"bold"});
instance.markRegExp(/true/,{"element":"span","className":"true"});
instance.markRegExp(/false/,{"element":"span","className":"false"});
</script>
</body>
</html>	
