<?php
require __DIR__ . '/SCTE35Parser.php';

$me = new SCTE35Parser();

$base64 = '';

//$arBase64 = array();
if (isset($_POST['base64']) && !empty($_POST['base64'])) {
	$base64 = $_POST['base64'];
}
$arBase64 = explode("\n", $base64);
$error = array();
$json = array();
$done = array();
if (!empty($base64)) {
	foreach ($arBase64 as $b64) {
		if (in_array($b64, $done)) continue;
		$done[] = $b64;
		try {
			$json[$b64] = $me->parseFromBase64orHex($b64);
		}
		catch (Exception $e) {
			$error[$b64] = $e->getMessage();
		}
	}
}
// Sort everything
function scteSort($a,$b) {
	$jsonA = json_decode($a);
	$ptsA = intval($jsonA->splice_command->pts_time);
	$jsonB = json_decode($b);
	$ptsB = intval($jsonB->splice_command->pts_time);
	if ($ptsA == $ptsB)
		return 0;
	return ($ptsA < $ptsB) ? -1 : 1;

}
uasort($json, 'scteSort');
$arBase64 = array_merge(array_keys($json), array_keys($error));

?><html>
<head>
<title>SCTE35 Decoder</title>
<style type="text/css">
div {font-size:0.8em;font-family: sans-serif;}
.rel {position:relative;}
.abs {position:absolute;}
#time {top:-2em;}
#descTitle { height:5em; width:10em;}
#desc { height:4em; }
.x02 { background:#FEE; }
.x10 { background:#C8C; }
.x11 { background:#C8C; }
.x22 { background:#C88; }
.x23 { background:#C88; }
.x30 { background:#88C; }
.x31 { background:#88C; }
.x34 { background:#8C8; }
.x35 { background:#8C8; }
.dupl { background:#FFF; }
</style>
</head>
<body>
<form name="scte" method="POST">
Enter Base64 message(s) : <br/>
(one per line, they will be de-duplicated if necessary)<br/>
<textarea name="base64" cols=200 rows=5><?php echo $base64;?></textarea>
<br/>
<br/>
<input type="submit">
</form>
<br/>
<form method="post">
        <input type="hidden" name="base64" value="" />
	<input type="submit" value="Empty" />
</form>
<br/>
<form method="post">
        <input type="hidden" name="base64" value="/DBjAAAAAAAAAP/wBQb/hlmXsgBNAhRDVUVJAAWg/3//AAEieoAAACIBAQIUQ1VFSQAFoAF//wAABX5AAAAwAAcCH0NVRUkABaD/f78MEEFERlIBM/EBND74BaADOkACAAAf8HKQ
/DB2AAAAAAAAAP/wBQb/hl8V8gBgAhZDVUVJAAWg/n//AAEc/EAAADQBAUQ3AhRDVUVJAAWgAn//AABSZcAAADABBwIfQ1VFSQAFoP9/vwwQQURGUgEz8QE0PvgFoAM6QAIAAAIPQ1VFSQAFoAF/vwAAMQAHll0Ikg==
/DBeAAAAAAAAAP/wBQb/hrH6QgBIAhRDVUVJAAWgA3//AAAiVRAAADACBwIfQ1VFSQAFoP9/vwwQQURGUgEz8QE0PvgFoAM6QAIAAAIPQ1VFSQAFoAJ/vwAAMQEH4zvzHw==
/DBeAAAAAAAAAP/wBQb/htTN4gBIAhRDVUVJAAWgBH//AAAbd0AAADADBwIfQ1VFSQAFoP9/vwwQQURGUgEz8QE0PvgFoAM6QAIAAAIPQ1VFSQAFoAN/vwAAMQIHTaq4Bg==
/DBeAAAAAAAAAP/wBQb/hvDDsgBIAhRDVUVJAAWgBX//AAAbd0AAADAEBwIfQ1VFSQAFoP9/vwwQQURGUgEz8QE0PvgFoAM6QAIAAAIPQ1VFSQAFoAR/vwAAMQMHOHvuFg==
/DBeAAAAAAAAAP/wBQb/hwy5ggBIAhRDVUVJAAWgBn//AAAiVRAAADAFBwIfQ1VFSQAFoP9/vwwQQURGUgEz8QE0PvgFoAM6QAIAAAIPQ1VFSQAFoAV/vwAAMQQH5FV9xw==
/DBeAAAAAAAAAP/wBQb/hy+NIgBIAhRDVUVJAAWgB3//AAAc1tAAADAGBwIfQ1VFSQAFoP9/vwwQQURGUgEz8QE0PvgFoAM6QAIAAAIPQ1VFSQAFoAZ/vwAAMQUH/vqzXg==
/DBeAAAAAAAAAP/wBQb/h0ziggBIAhRDVUVJAAWgCH//AAApMuAAADAHBwIfQ1VFSQAFoP9/vwwQQURGUgEz8QE0PvgFoAM6QAIAAAIPQ1VFSQAFoAd/vwAAMQYHCx8XEQ==
/DA9AAAAAAAAAP/wBQb/h3aT8gAnAhRDVUVJAAWgCX//AAAFfkAAADAAAAIPQ1VFSQAFoAh/vwAAMQcHm1LUxw==
/DBJAAAAAAAAAP/wBQb/h3wSMgAzAg9DVUVJAAWg/n+/AAA1AQECD0NVRUkABaD/f78AACMBAQIPQ1VFSQAFoAl/vwAAMQAAksEc7A==
/DBjAAAAAAAAAP/wBQb/km2VsgBNAhRDVUVJAAXc/3//AAEilqAAACIBAQIUQ1VFSQAF3AF//wAABX5AAAAwAAoCH0NVRUkABdz/f78MEEFERlIBM/EBND74BdwDOpACAAAjN6Xj
/DB2AAAAAAAAAP/wBQb/knMT8gBgAhZDVUVJAAXc/n//AAEdGGAAADQBAUQ3AhRDVUVJAAXcAn//AAApMuAAADABCgIfQ1VFSQAF3P9/vwwQQURGUgEz8QE0PvgF3AM6kAIAAAIPQ1VFSQAF3AF/vwAAMQAKoEtv+g==
/DBeAAAAAAAAAP/wBQb/kpzFYgBIAhRDVUVJAAXcA3//AAANu6AAADACCgIfQ1VFSQAF3P9/vwwQQURGUgEz8QE0PvgF3AM6kAIAAAIPQ1VFSQAF3AJ/vwAAMQEKQ/UNhA==
/DBeAAAAAAAAAP/wBQb/kqr/kgBIAhRDVUVJAAXcBH//AAAbd0AAADADCgIfQ1VFSQAF3P9/vwwQQURGUgEz8QE0PvgF3AM6kAIAAAIPQ1VFSQAF3AN/vwAAMQIKujMZ9g==
/DBeAAAAAAAAAP/wBQb/ksb1YgBIAhRDVUVJAAXcBX//AAAUmXAAADAECgIfQ1VFSQAF3P9/vwwQQURGUgEz8QE0PvgF3AM6kAIAAAIPQ1VFSQAF3AR/vwAAMQMKTh4Gkw==
/DBeAAAAAAAAAP/wBQb/ktwNYgBIAhRDVUVJAAXcBn//AAAbd0AAADAFCgIfQ1VFSQAF3P9/vwwQQURGUgEz8QE0PvgF3AM6kAIAAAIPQ1VFSQAF3AV/vwAAMQQKKCXCLw==
/DBeAAAAAAAAAP/wBQb/kvgDMgBIAhRDVUVJAAXcB3//AAApMuAAADAGCgIfQ1VFSQAF3P9/vwwQQURGUgEz8QE0PvgF3AM6kAIAAAIPQ1VFSQAF3AZ/vwAAMQUKwV0YYQ==
/DBeAAAAAAAAAP/wBQb/kyG0ogBIAhRDVUVJAAXcCH//AAAbd0AAADAHCgIfQ1VFSQAF3P9/vwwQQURGUgEz8QE0PvgF3AM6kAIAAAIPQ1VFSQAF3Ad/vwAAMQYKqSPraQ==
/DBeAAAAAAAAAP/wBQb/kz2qcgBIAhRDVUVJAAXcCX//AAAbd0AAADAICgIfQ1VFSQAF3P9/vwwQQURGUgEz8QE0PvgF3AM6kAIAAAIPQ1VFSQAF3Ah/vwAAMQcKXiX2vA==
/DBeAAAAAAAAAP/wBQb/k1mgQgBIAhRDVUVJAAXcCn//AAAUmXAAADAJCgIfQ1VFSQAF3P9/vwwQQURGUgEz8QE0PvgF3AM6kAIAAAIPQ1VFSQAF3Al/vwAAMQgK7+7lww==
/DBeAAAAAAAAAP/wBQb/k264QgBIAhRDVUVJAAXcC3//AAAbd0AAADAKCgIfQ1VFSQAF3P9/vwwQQURGUgEz8QE0PvgF3AM6kAIAAAIPQ1VFSQAF3Ap/vwAAMQkKRFdZ/w==
/DA9AAAAAAAAAP/wBQb/k4quEgAnAhRDVUVJAAXcDH//AAAFfkAAADAAAAIPQ1VFSQAF3At/vwAAMQoKh1aO7Q==
/DBJAAAAAAAAAP/wBQb/k5AsUgAzAg9DVUVJAAXc/n+/AAA1AQECD0NVRUkABdz/f78AACMBAQIPQ1VFSQAF3Ax/vwAAMQAAzmFSAg==
/DAnAAAAAAAAAP/wBQb/m0WXogARAg9DVUVJABGOH3+/AAARAQGNexd2
/DAsAAAAAAAAAP/wBQb/m0WXogAWAhRDVUVJARjh8n//AAAV+QAAACIBAdZpDIs=
/DAnAAAAAAAAAP/wBQb/m1uQogARAg9DVUVJARjh8n+/AAAjAQFAWkDZ
/DBjAAAAAAAAAP/wBQb/m9NtAgBNAhRDVUVJAAX6/3//AAB99VAAACIBAQIUQ1VFSQAF+gF//wAABX5AAAAwAAICH0NVRUkABfr/f78MEEFERlIBM/EBND74BfoBZkgCAAAD8Cbc
/DB2AAAAAAAAAP/wBQb/m9jrQgBgAhZDVUVJAAX6/n//AAB4dxAAADQBAUQ3AhRDVUVJAAX6An//AABSZcAAADABAgIfQ1VFSQAF+v9/vwwQQURGUgEz8QE0PvgF+gFmSAIAAAIPQ1VFSQAF+gF/vwAAMQAC7I+NZQ==
/DBeAAAAAAAAAP/wBQb/nC/uQgBIAhRDVUVJAAX6A3//AAAbd0AAADACAgIfQ1VFSQAF+v9/vwwQQURGUgEz8QE0PvgF+gFmSAIAAAIPQ1VFSQAF+gJ/vwAAMQECdWxi9A==
/DA9AAAAAAAAAP/wBQb/nEvkEgAnAhRDVUVJAAX6BX//AAAFfkAAADAAAAIPQ1VFSQAF+gR/vwAAMQICXVNuoQ==
/DBJAAAAAAAAAP/wBQb/nFFiUgAzAg9DVUVJAAX6/n+/AAA1AQECD0NVRUkABfr/f78AACMBAQIPQ1VFSQAF+gV/vwAAMQAAlTVL4g==
/DBjAAAAAAAAAP/wBQb/nYoOEgBNAhRDVUVJAAYY/3//AACOjDAAACIBAQIUQ1VFSQAGGAF//wAABX5AAAAwAAUCH0NVRUkABhj/f78MEEFERlIBM/EBND74BhgBlXgCAABDqj9T
/DB2AAAAAAAAAP/wBQb/nY+MUgBgAhZDVUVJAAYY/n//AACJDfAAADQBAUQ3AhRDVUVJAAYYAn//AAAg9YAAADABBQIfQ1VFSQAGGP9/vwwQQURGUgEz8QE0PvgGGAGVeAIAAAIPQ1VFSQAGGAF/vwAAMQAF9ZyxvA==
/DBeAAAAAAAAAP/wBQb/nbEAYgBIAhRDVUVJAAYYA3//AAApMuAAADACBQIfQ1VFSQAGGP9/vwwQQURGUgEz8QE0PvgGGAGVeAIAAAIPQ1VFSQAGGAJ/vwAAMQEFDQTbng==
/DBeAAAAAAAAAP/wBQb/ndqx0gBIAhRDVUVJAAYYBH//AAAUmXAAADADBQIfQ1VFSQAGGP9/vwwQQURGUgEz8QE0PvgGGAGVeAIAAAIPQ1VFSQAGGAN/vwAAMQIFyovJdw==
/DBeAAAAAAAAAP/wBQb/ne/J0gBIAhRDVUVJAAYYBX//AAAUmXAAADAEBQIfQ1VFSQAGGP9/vwwQQURGUgEz8QE0PvgGGAGVeAIAAAIPQ1VFSQAGGAR/vwAAMQMFPi+EcA==
/DBeAAAAAAAAAP/wBQb/ngTh0gBIAhRDVUVJAAYYBn//AAANu6AAADAFBQIfQ1VFSQAGGP9/vwwQQURGUgEz8QE0PvgGGAGVeAIAAAIPQ1VFSQAGGAV/vwAAMQQF9SN4Bw==
/DA9AAAAAAAAAP/wBQb/nhMcAgAnAhRDVUVJAAYYB3//AAAFfkAAADAAAAIPQ1VFSQAGGAZ/vwAAMQUFEQarfA==
/DBJAAAAAAAAAP/wBQb/nhiaQgAzAg9DVUVJAAYY/n+/AAA1AQECD0NVRUkABhj/f78AACMBAQIPQ1VFSQAGGAd/vwAAMQAAFBzQSw==
/DA9AAAAAAAAAP/wBQb/np4yQgAnAhRDVUVJARCwwX//AAAV+QAAACIBAQIPQ1VFSQARCwx/vwAAEAEBEkAg9A==
/DAnAAAAAAAAAP/wBQb/nrQrQgARAg9DVUVJARCwwX+/AAAjAQHwynl2
/DBjAAAAAAAAAP/wBQb/qcSqAgBNAhRDVUVJAAZe/3//AAGDtSAAACIBAQIUQ1VFSQAGXgF//wAABX5AAAAwAAwCH0NVRUkABl7/f78MEEFERlIBM/EBND74Bl4ETtACAACaSfpr
/DB2AAAAAAAAAP/wBQb/qcooQgBgAhZDVUVJAAZe/n//AAF+NuAAADQBAUQ3AhRDVUVJAAZeAn//AAAUmXAAADABDAIfQ1VFSQAGXv9/vwwQQURGUgEz8QE0PvgGXgRO0AIAAAIPQ1VFSQAGXgF/vwAAMQAMlRK/GQ==
/DBeAAAAAAAAAP/wBQb/qd9AQgBIAhRDVUVJAAZeA3//AAAbd0AAADACDAIfQ1VFSQAGXv9/vwwQQURGUgEz8QE0PvgGXgRO0AIAAAIPQ1VFSQAGXgJ/vwAAMQEMGeijWA==
/DBeAAAAAAAAAP/wBQb/qfs2EgBIAhRDVUVJAAZeBH//AAApMuAAADADDAIfQ1VFSQAGXv9/vwwQQURGUgEz8QE0PvgGXgRO0AIAAAIPQ1VFSQAGXgN/vwAAMQIMPm45CQ==
/DBeAAAAAAAAAP/wBQb/qiTnggBIAhRDVUVJAAZeBX//AAAbd0AAADAEDAIfQ1VFSQAGXv9/vwwQQURGUgEz8QE0PvgGXgRO0AIAAAIPQ1VFSQAGXgR/vwAAMQMM00vi5w==
/DBeAAAAAAAAAP/wBQb/qkDdUgBIAhRDVUVJAAZeBn//AAAbd0AAADAFDAIfQ1VFSQAGXv9/vwwQQURGUgEz8QE0PvgGXgRO0AIAAAIPQ1VFSQAGXgV/vwAAMQQMpb+lWA==
/DBeAAAAAAAAAP/wBQb/qlzTIgBIAhRDVUVJAAZeB3//AAAiVRAAADAGDAIfQ1VFSQAGXv9/vwwQQURGUgEz8QE0PvgGXgRO0AIAAAIPQ1VFSQAGXgZ/vwAAMQUMIVpigw==
/DBeAAAAAAAAAP/wBQb/qn+mwgBIAhRDVUVJAAZeCH//AAAUmXAAADAHDAIfQ1VFSQAGXv9/vwwQQURGUgEz8QE0PvgGXgRO0AIAAAIPQ1VFSQAGXgd/vwAAMQYMpckm8w==
/DBeAAAAAAAAAP/wBQb/qpS+wgBIAhRDVUVJAAZeCX//AAApMuAAADAIDAIfQ1VFSQAGXv9/vwwQQURGUgEz8QE0PvgGXgRO0AIAAAIPQ1VFSQAGXgh/vwAAMQcMjxQmuw==
/DBeAAAAAAAAAP/wBQb/qr5wMgBIAhRDVUVJAAZeCn//AAApMuAAADAJDAIfQ1VFSQAGXv9/vwwQQURGUgEz8QE0PvgGXgRO0AIAAAIPQ1VFSQAGXgl/vwAAMQgM0YyaJw==
/DBeAAAAAAAAAP/wBQb/qughogBIAhRDVUVJAAZeC3//AAApMuAAADAKDAIfQ1VFSQAGXv9/vwwQQURGUgEz8QE0PvgGXgRO0AIAAAIPQ1VFSQAGXgp/vwAAMQkMfSGnLw==
/DBeAAAAAAAAAP/wBQb/qxHTEgBIAhRDVUVJAAZeDH//AAAbd0AAADALDAIfQ1VFSQAGXv9/vwwQQURGUgEz8QE0PvgGXgRO0AIAAAIPQ1VFSQAGXgt/vwAAMQoM3pvNIQ==
/DBeAAAAAAAAAP/wBQb/qy3I4gBIAhRDVUVJAAZeDX//AAAUmXAAADAMDAIfQ1VFSQAGXv9/vwwQQURGUgEz8QE0PvgGXgRO0AIAAAIPQ1VFSQAGXgx/vwAAMQsMNHLxnw==
/DA9AAAAAAAAAP/wBQb/q0Lg4gAnAhRDVUVJAAZeDn//AAAFfkAAADAAAAIPQ1VFSQAGXg1/vwAAMQwMB/EjnQ==
/DBJAAAAAAAAAP/wBQb/q0hfIgAzAg9DVUVJAAZe/n+/AAA1AQECD0NVRUkABl7/f78AACMBAQIPQ1VFSQAGXg5/vwAAMQAADnfkuw==
/DBjAAAAAAAAAP/wBQb/sx+S4gBNAhRDVUVJAAau/3//AAFTJeAAACIBAQIUQ1VFSQAGrgF//wAABX5AAAAwAAsCH0NVRUkABq7/f78MEEFERlIBM/EBND74Bq4DxLACAAD8brxd
/DB2AAAAAAAAAP/wBQb/syURIgBgAhZDVUVJAAau/n//AAFNp6AAADQBAUQ3AhRDVUVJAAauAn//AAAUmXAAADABCwIfQ1VFSQAGrv9/vwwQQURGUgEz8QE0PvgGrgPEsAIAAAIPQ1VFSQAGrgF/vwAAMQALyMo6YQ==
/DBeAAAAAAAAAP/wBQb/szopIgBIAhRDVUVJAAauA3//AAAbd0AAADACCwIfQ1VFSQAGrv9/vwwQQURGUgEz8QE0PvgGrgPEsAIAAAIPQ1VFSQAGrgJ/vwAAMQELOBjErA==
/DBeAAAAAAAAAP/wBQb/s1Ye8gBIAhRDVUVJAAauBH//AAApMuAAADADCwIfQ1VFSQAGrv9/vwwQQURGUgEz8QE0PvgGrgPEsAIAAAIPQ1VFSQAGrgN/vwAAMQILFdJg5w==
/DBeAAAAAAAAAP/wBQb/s3/QYgBIAhRDVUVJAAauBX//AAApMuAAADAECwIfQ1VFSQAGrv9/vwwQQURGUgEz8QE0PvgGrgPEsAIAAAIPQ1VFSQAGrgR/vwAAMQMLAXrUOA==
/DBeAAAAAAAAAP/wBQb/s6mB0gBIAhRDVUVJAAauBn//AAAbd0AAADAFCwIfQ1VFSQAGrv9/vwwQQURGUgEz8QE0PvgGrgPEsAIAAAIPQ1VFSQAGrgV/vwAAMQQLeIN6qQ==
/DBeAAAAAAAAAP/wBQb/s8V3ogBIAhRDVUVJAAauB3//AAAbd0AAADAGCwIfQ1VFSQAGrv9/vwwQQURGUgEz8QE0PvgGrgPEsAIAAAIPQ1VFSQAGrgZ/vwAAMQUL47KmXQ==
/DBeAAAAAAAAAP/wBQb/s+FtcgBIAhRDVUVJAAauCH//AAAbd0AAADAHCwIfQ1VFSQAGrv9/vwwQQURGUgEz8QE0PvgGrgPEsAIAAAIPQ1VFSQAGrgd/vwAAMQYLMk/pww==
/DBeAAAAAAAAAP/wBQb/s/1jQgBIAhRDVUVJAAauCX//AAAbd0AAADAICwIfQ1VFSQAGrv9/vwwQQURGUgEz8QE0PvgGrgPEsAIAAAIPQ1VFSQAGrgh/vwAAMQcLo0romg==
/DBeAAAAAAAAAP/wBQb/tBlZEgBIAhRDVUVJAAauCn//AAAUmXAAADAJCwIfQ1VFSQAGrv9/vwwQQURGUgEz8QE0PvgGrgPEsAIAAAIPQ1VFSQAGrgl/vwAAMQgLUWJYNA==
/DBeAAAAAAAAAP/wBQb/tC5xEgBIAhRDVUVJAAauC3//AAAiVRAAADAKCwIfQ1VFSQAGrv9/vwwQQURGUgEz8QE0PvgGrgPEsAIAAAIPQ1VFSQAGrgp/vwAAMQkLwCwGLg==
/DBeAAAAAAAAAP/wBQb/tFFEsgBIAhRDVUVJAAauDH//AAAbd0AAADALCwIfQ1VFSQAGrv9/vwwQQURGUgEz8QE0PvgGrgPEsAIAAAIPQ1VFSQAGrgt/vwAAMQoLCTIOXg==
/DA9AAAAAAAAAP/wBQb/tG06ggAnAhRDVUVJAAauDX//AAAFfkAAADAAAAIPQ1VFSQAGrgx/vwAAMQsLoFQ9Pw==
/DBJAAAAAAAAAP/wBQb/tHK4wgAzAg9DVUVJAAau/n+/AAA1AQECD0NVRUkABq7/f78AACMBAQIPQ1VFSQAGrg1/vwAAMQAAlrwXVw==
/DAnAAAAAAAAAP/wBQb/u95eIgARAg9DVUVJABELDH+/AAARAQE2l5yL
/DAsAAAAAAAAAP/wBQb/u95eIgAWAhRDVUVJARCwwn//AAAV+QAAACIBAd1A+5w=
/DAnAAAAAAAAAP/wBQb/u/RXIgARAg9DVUVJARCwwn+/AAAjAQFBJ6Ed
/DA9AAAAAAAAAP/wBQb/vJvFogAnAhRDVUVJASDioX//AAAV+QAAACIBAQIPQ1VFSQASDip/vwAAEAEBgInOYQ==
/DAnAAAAAAAAAP/wBQb/vLG+ogARAg9DVUVJASDioX+/AAAjAQEMM0Gj" />
	<input type="submit" value="2020-12-08 17h40 TF1" />
</form>
<br/>
<form method="post">
        <input type="hidden" name="base64" value="/DBoAAAAAAAAAP/wBQb+8dUVUABSAhRDVUVJAAAFqn/AAAE0/ZAAACIBAQIUQ1VFSQAAAAB/wAAABt3QAAAwAAACJENVRUkAAAWqf8AAAAAAAAwQQURGUgEz8gE0PvgFqgNu6AIAADQFnvo=
/DB+AAAAAAAAAP/wBQb+8dvzIABoAhRDVUVJAAAAAH/AAAAAAAAAADEAAAIUQ1VFSQAAAAF/wAAANu6AAAAwAQkCFENVRUkAAAWqf8AAAS4fwAAANAEBAiRDVUVJAAAFqn/AAAAAAAAMEEFERlIBM/IBND74BaoDbugCAAA8Y9Cw
/DBoAAAAAAAAAP/wBQb+8hRBMABSAhRDVUVJAAAAAX/AAAAAAAAAADEAAAIUQ1VFSQAAAAJ/wAAAKTLgAAAwAgkCJENVRUkAAAWqf8AAAAAAAAwQQURGUgEz8gE0PvgFqgNu6AIAAKC6MSs=
/DBoAAAAAAAAAP/wBQb+8j7ToABSAhRDVUVJAAAAAn/AAAAAAAAAADEAAAIUQ1VFSQAAAAN/wAAAEHrAAAAwAwkCJENVRUkAAAWqf8AAAAAAAAwQQURGUgEz8gE0PvgFqgNu6AIAAH/4Yag=
/DBoAAAAAAAAAP/wBQb+8lCt8ABSAhRDVUVJAAAAA3/AAAAAAAAAADEAAAIUQ1VFSQAAAAR/wAAADbugAAAwBAkCJENVRUkAAAWqf8AAAAAAAAwQQURGUgEz8gE0PvgFqgNu6AIAAJ74EP4=
/DBoAAAAAAAAAP/wBQb+8l/JIABSAhRDVUVJAAAABH/AAAAAAAAAADEAAAIUQ1VFSQAAAAV/wAAAKTLgAAAwBQkCJENVRUkAAAWqf8AAAAAAAAwQQURGUgEz8gE0PvgFqgNu6AIAAFKDmuw=
/DBoAAAAAAAAAP/wBQb+8opbkABSAhRDVUVJAAAABX/AAAAAAAAAADEAAAIUQ1VFSQAAAAZ/wAAAG3dAAAAwBgkCJENVRUkAAAWqf8AAAAAAAAwQQURGUgEz8gE0PvgFqgNu6AIAAM5krh8=
/DBoAAAAAAAAAP/wBQb+8qcyYABSAhRDVUVJAAAABn/AAAAAAAAAADEAAAIUQ1VFSQAAAAd/wAAAG3dAAAAwBwkCJENVRUkAAAWqf8AAAAAAAAwQQURGUgEz8gE0PvgFqgNu6AIAAB+lQ30=
/DBoAAAAAAAAAP/wBQb+8sQJMABSAhRDVUVJAAAAB3/AAAAAAAAAADEAAAIUQ1VFSQAAAAh/wAAAFJlwAAAwCAkCJENVRUkAAAWqf8AAAAAAAAwQQURGUgEz8gE0PvgFqgNu6AIAAKK9eNg=
/DBoAAAAAAAAAP/wBQb+8toCMABSAhRDVUVJAAAACH/AAAAAAAAAADEAAAIUQ1VFSQAAAAl/wAAAKTLgAAAwCQkCJENVRUkAAAWqf8AAAAAAAAwQQURGUgEz8gE0PvgFqgNu6AIAABc7ueY=
/DBCAAAAAAAAAP/wBQb+8wSUoAAsAhRDVUVJAAAACX/AAAAAAAAAADEAAAIUQ1VFSQAAAAp/wAAABX5AAAAwAADZrneL
/DBYAAAAAAAAAP/wBQb+8woS4ABCAhRDVUVJAAAACn/AAAAAAAAAADEAAAIUQ1VFSQAABap/wAAAAAAAAAAjAQECFENVRUkAAAWqf8AAAAAAAAAANQEBeiMIjA==
/DBoAAAAAAAAAP/wBQb+806u8ABSAhRDVUVJAAAFr3/AAAFlDkAAACIBAQIUQ1VFSQAAAAB/wAAABt3QAAAwAAACJENVRUkAAAWvf8AAAAAAAAwQQURGUgEz8gE0PvgFrwP3oAIAAPtIL8Q=
/DB+AAAAAAAAAP/wBQb+81WMwABoAhRDVUVJAAAAAH/AAAAAAAAAADEAAAIUQ1VFSQAAAAF/wAAAKTLgAAAwAQsCFENVRUkAAAWvf8AAAV4wcAAANAEBAiRDVUVJAAAFr3/AAAAAAAAMEEFERlIBM/IBND74Ba8D96ACAAA3/wiH
/DBoAAAAAAAAAP/wBQb+84AfMABSAhRDVUVJAAAAAX/AAAAAAAAAADEAAAIUQ1VFSQAAAAJ/wAAAJRQwAAAwAgsCJENVRUkAAAWvf8AAAAAAAAwQQURGUgEz8gE0PvgFrwP3oAIAALfLQpc=
/DBoAAAAAAAAAP/wBQb+86aS8ABSAhRDVUVJAAAAAn/AAAAAAAAAADEAAAIUQ1VFSQAAAAN/wAAAG3dAAAAwAwsCJENVRUkAAAWvf8AAAAAAAAwQQURGUgEz8gE0PvgFrwP3oAIAAAMro1g=
/DBoAAAAAAAAAP/wBQb+88NpwABSAhRDVUVJAAAAA3/AAAAAAAAAADEAAAIUQ1VFSQAAAAR/wAAADFwQAAAwBAsCJENVRUkAAAWvf8AAAAAAAAwQQURGUgEz8gE0PvgFrwP3oAIAAK97xvc=
/DBoAAAAAAAAAP/wBQb+89ElYABSAhRDVUVJAAAABH/AAAAAAAAAADEAAAIUQ1VFSQAAAAV/wAAAGhewAAAwBQsCJENVRUkAAAWvf8AAAAAAAAwQQURGUgEz8gE0PvgFrwP3oAIAAAGCAiQ=
/DBoAAAAAAAAAP/wBQb+8+ycoABSAhRDVUVJAAAABX/AAAAAAAAAADEAAAIUQ1VFSQAAAAZ/wAAAG3dAAAAwBgsCJENVRUkAAAWvf8AAAAAAAAwQQURGUgEz8gE0PvgFrwP3oAIAAJLkz3Y=
/DBoAAAAAAAAAP/wBQb+9AlzcABSAhRDVUVJAAAABn/AAAAAAAAAADEAAAIUQ1VFSQAAAAd/wAAAFJlwAAAwBwsCJENVRUkAAAWvf8AAAAAAAAwQQURGUgEz8gE0PvgFrwP3oAIAAMX+aOc=
/DBoAAAAAAAAAP/wBQb+9B9scABSAhRDVUVJAAAAB3/AAAAAAAAAADEAAAIUQ1VFSQAAAAh/wAAAG3dAAAAwCAsCJENVRUkAAAWvf8AAAAAAAAwQQURGUgEz8gE0PvgFrwP3oAIAAEiSGJQ=
/DBoAAAAAAAAAP/wBQb+9DxDQABSAhRDVUVJAAAACH/AAAAAAAAAADEAAAIUQ1VFSQAAAAl/wAAAKTLgAAAwCQsCJENVRUkAAAWvf8AAAAAAAAwQQURGUgEz8gE0PvgFrwP3oAIAAPVNr1g=
/DBoAAAAAAAAAP/wBQb+9GbVsABSAhRDVUVJAAAACX/AAAAAAAAAADEAAAIUQ1VFSQAAAAp/wAAAG3dAAAAwCgsCJENVRUkAAAWvf8AAAAAAAAwQQURGUgEz8gE0PvgFrwP3oAIAACRegZY=
/DBoAAAAAAAAAP/wBQb+9IOsgABSAhRDVUVJAAAACn/AAAAAAAAAADEAAAIUQ1VFSQAAAAt/wAAAKTLgAAAwCwsCJENVRUkAAAWvf8AAAAAAAAwQQURGUgEz8gE0PvgFrwP3oAIAAM76Ps8=
/DBCAAAAAAAAAP/wBQb+9K4+8AAsAhRDVUVJAAAAC3/AAAAAAAAAADEAAAIUQ1VFSQAAAAx/wAAABX5AAAAwAAB7xksb
/DBYAAAAAAAAAP/wBQb+9LO9MABCAhRDVUVJAAAADH/AAAAAAAAAADEAAAIUQ1VFSQAABa9/wAAAAAAAAAAjAQECFENVRUkAAAWvf8AAAAAAAAAANQEBVBln+w==
/DBoAAAAAAAAAP/wBQb/Bfhc4ABSAhRDVUVJAAAGSn/AAAFiTyAAACIBAQIUQ1VFSQAAAAB/wAAABt3QAAAwAAACJENVRUkAAAZKf8AAAAAAAAwQQURGUgEz8gE0PvgGSgPv0AIAAKKBRPY=
/DB+AAAAAAAAAP/wBQb/Bf86sABoAhRDVUVJAAAAAH/AAAAAAAAAADEAAAIUQ1VFSQAAAAF/wAAAG3dAAAAwAQkCFENVRUkAAAZKf8AAAVtxUAAANAEBAiRDVUVJAAAGSn/AAAAAAAAMEEFERlIBM/IBND74BkoD79ACAAAcgV1v
/DBoAAAAAAAAAP/wBQb/BhwRgABSAhRDVUVJAAAAAX/AAAAAAAAAADEAAAIUQ1VFSQAAAAJ/wAAAKTLgAAAwAgkCJENVRUkAAAZKf8AAAAAAAAwQQURGUgEz8gE0PvgGSgPv0AIAABr9Io8=
/DBoAAAAAAAAAP/wBQb/Bkaj8ABSAhRDVUVJAAAAAn/AAAAAAAAAADEAAAIUQ1VFSQAAAAN/wAAAGLggAAAwAwkCJENVRUkAAAZKf8AAAAAAAAwQQURGUgEz8gE0PvgGSgPv0AIAAKRlZfU=
/DBoAAAAAAAAAP/wBQb/BmC7oABSAhRDVUVJAAAAA3/AAAAAAAAAADEAAAIUQ1VFSQAAAAR/wAAALFRwAAAwBAkCJENVRUkAAAZKf8AAAAAAAAwQQURGUgEz8gE0PvgGSgPv0AIAAKB4vuI=
/DBoAAAAAAAAAP/wBQb/Bo4NMABSAhRDVUVJAAAABH/AAAAAAAAAADEAAAIUQ1VFSQAAAAV/wAAAKTLgAAAwBQkCJENVRUkAAAZKf8AAAAAAAAwQQURGUgEz8gE0PvgGSgPv0AIAAOyWq5I=
/DBoAAAAAAAAAP/wBQb/BrifoABSAhRDVUVJAAAABX/AAAAAAAAAADEAAAIUQ1VFSQAAAAZ/wAAAKTLgAAAwBgkCJENVRUkAAAZKf8AAAAAAAAwQQURGUgEz8gE0PvgGSgPv0AIAAIssJ6c=
/DBoAAAAAAAAAP/wBQb/BuMyEABSAhRDVUVJAAAABn/AAAAAAAAAADEAAAIUQ1VFSQAAAAd/wAAAKTLgAAAwBwkCJENVRUkAAAZKf8AAAAAAAAwQQURGUgEz8gE0PvgGSgPv0AIAAKIedIY=
/DBoAAAAAAAAAP/wBQb/Bw3EgABSAhRDVUVJAAAAB3/AAAAAAAAAADEAAAIUQ1VFSQAAAAh/wAAAKTLgAAAwCAkCJENVRUkAAAZKf8AAAAAAAAwQQURGUgEz8gE0PvgGSgPv0AIAAKDKKrQ=
/DBoAAAAAAAAAP/wBQb/BzhW8ABSAhRDVUVJAAAACH/AAAAAAAAAADEAAAIUQ1VFSQAAAAl/wAAAG3dAAAAwCQkCJENVRUkAAAZKf8AAAAAAAAwQQURGUgEz8gE0PvgGSgPv0AIAAJ+lQSk=
/DBCAAAAAAAAAP/wBQb/B1UtwAAsAhRDVUVJAAAACX/AAAAAAAAAADEAAAIUQ1VFSQAAAAp/wAAABX5AAAAwAADuwaS2
/DBYAAAAAAAAAP/wBQb/B1qsAABCAhRDVUVJAAAACn/AAAAAAAAAADEAAAIUQ1VFSQAABkp/wAAAAAAAAAAjAQECFENVRUkAAAZKf8AAAAAAAAAANQEB+nKnQg==
/DBoAAAAAAAAAP/wBQb/B5+ccABSAhRDVUVJAAAGWX/AAAFBWaAAACIBAQIUQ1VFSQAAAAB/wAAABt3QAAAwAAACJENVRUkAAAZZf8AAAAAAAAwQQURGUgEz8gE0PvgGWQOSEAIAAO2Nai8=
/DB+AAAAAAAAAP/wBQb/B6Z6QABoAhRDVUVJAAAAAH/AAAAAAAAAADEAAAIUQ1VFSQAAAAF/wAAAFJlwAAAwAQgCFENVRUkAAAZZf8AAATp70AAANAEBAiRDVUVJAAAGWX/AAAAAAAAMEEFERlIBM/IBND74BlkDkhACAAD/Mvbc
/DBoAAAAAAAAAP/wBQb/B7xzQABSAhRDVUVJAAAAAX/AAAAAAAAAADEAAAIUQ1VFSQAAAAJ/wAAAKTLgAAAwAggCJENVRUkAAAZZf8AAAAAAAAwQQURGUgEz8gE0PvgGWQOSEAIAAKkk/QY=
/DBoAAAAAAAAAP/wBQb/B+cFsABSAhRDVUVJAAAAAn/AAAAAAAAAADEAAAIUQ1VFSQAAAAN/wAAAIlUQAAAwAwgCJENVRUkAAAZZf8AAAAAAAAwQQURGUgEz8gE0PvgGWQOSEAIAAOmUpUI=
/DBoAAAAAAAAAP/wBQb/CAq6UABSAhRDVUVJAAAAA3/AAAAAAAAAADEAAAIUQ1VFSQAAAAR/wAAADbugAAAwBAgCJENVRUkAAAZZf8AAAAAAAAwQQURGUgEz8gE0PvgGWQOSEAIAAD/PtS8=
/DBoAAAAAAAAAP/wBQb/CBnVgABSAhRDVUVJAAAABH/AAAAAAAAAADEAAAIUQ1VFSQAAAAV/wAAALFRwAAAwBQgCJENVRUkAAAZZf8AAAAAAAAwQQURGUgEz8gE0PvgGWQOSEAIAAK6sW9A=
/DBoAAAAAAAAAP/wBQb/CEcnEABSAhRDVUVJAAAABX/AAAAAAAAAADEAAAIUQ1VFSQAAAAZ/wAAAUmXAAAAwBggCJENVRUkAAAZZf8AAAAAAAAwQQURGUgEz8gE0PvgGWQOSEAIAAB+tnV8=
/DBoAAAAAAAAAP/wBQb/CJrsYABSAhRDVUVJAAAABn/AAAAAAAAAADEAAAIUQ1VFSQAAAAd/wAAAKTLgAAAwBwgCJENVRUkAAAZZf8AAAAAAAAwQQURGUgEz8gE0PvgGWQOSEAIAAJ0naig=
/DBoAAAAAAAAAP/wBQb/CMV+0ABSAhRDVUVJAAAAB3/AAAAAAAAAADEAAAIUQ1VFSQAAAAh/wAAAFJlwAAAwCAgCJENVRUkAAAZZf8AAAAAAAAwQQURGUgEz8gE0PvgGWQOSEAIAAM2Npxs=
/DBCAAAAAAAAAP/wBQb/CNt30AAsAhRDVUVJAAAACH/AAAAAAAAAADEAAAIUQ1VFSQAAAAl/wAAABX5AAAAwAAAMcTiC
/DBYAAAAAAAAAP/wBQb/COD2EABCAhRDVUVJAAAACX/AAAAAAAAAADEAAAIUQ1VFSQAABll/wAAAAAAAAAAjAQECFENVRUkAAAZZf8AAAAAAAAAANQEBgysU9g==
/DBoAAAAAAAAAP/wBQb/GEGVEABSAhRDVUVJAAAGs3/AAAF26JAAACIBAQIUQ1VFSQAAAAB/wAAABt3QAAAwAAACJENVRUkAAAazf8AAAAAAAAwQQURGUgEz8gE0PvgGswQqaAIAANXiMYs=
/DB+AAAAAAAAAP/wBQb/GEhy4ABoAhRDVUVJAAAAAH/AAAAAAAAAADEAAAIUQ1VFSQAAAAF/wAAAFJlwAAAwAQsCFENVRUkAAAazf8AAAXAKwAAANAEBAiRDVUVJAAAGs3/AAAAAAAAMEEFERlIBM/IBND74BrMEKmgCAACrg0CF
/DBoAAAAAAAAAP/wBQb/GF5r4ABSAhRDVUVJAAAAAX/AAAAAAAAAADEAAAIUQ1VFSQAAAAJ/wAAAG3dAAAAwAgsCJENVRUkAAAazf8AAAAAAAAwQQURGUgEz8gE0PvgGswQqaAIAAM1cMnQ=
/DBoAAAAAAAAAP/wBQb/GHtCsABSAhRDVUVJAAAAAn/AAAAAAAAAADEAAAIUQ1VFSQAAAAN/wAAADbugAAAwAwsCJENVRUkAAAazf8AAAAAAAAwQQURGUgEz8gE0PvgGswQqaAIAAPXde2I=
/DBoAAAAAAAAAP/wBQb/GIpd4ABSAhRDVUVJAAAAA3/AAAAAAAAAADEAAAIUQ1VFSQAAAAR/wAAAKTLgAAAwBAsCJENVRUkAAAazf8AAAAAAAAwQQURGUgEz8gE0PvgGswQqaAIAAMRI604=
/DBoAAAAAAAAAP/wBQb/GLTwUABSAhRDVUVJAAAABH/AAAAAAAAAADEAAAIUQ1VFSQAAAAV/wAAAKTLgAAAwBQsCJENVRUkAAAazf8AAAAAAAAwQQURGUgEz8gE0PvgGswQqaAIAAO03Gj4=
/DBoAAAAAAAAAP/wBQb/GN+CwABSAhRDVUVJAAAABX/AAAAAAAAAADEAAAIUQ1VFSQAAAAZ/wAAAKTLgAAAwBgsCJENVRUkAAAazf8AAAAAAAAwQQURGUgEz8gE0PvgGswQqaAIAALRJ+N0=
/DBoAAAAAAAAAP/wBQb/GQoVMABSAhRDVUVJAAAABn/AAAAAAAAAADEAAAIUQ1VFSQAAAAd/wAAACvyAAAAwBwsCJENVRUkAAAazf8AAAAAAAAwQQURGUgEz8gE0PvgGswQqaAIAAG9Gp48=
/DBoAAAAAAAAAP/wBQb/GRZxQABSAhRDVUVJAAAAB3/AAAAAAAAAADEAAAIUQ1VFSQAAAAh/wAAAG3dAAAAwCAsCJENVRUkAAAazf8AAAAAAAAwQQURGUgEz8gE0PvgGswQqaAIAAKFIDKY=
/DBoAAAAAAAAAP/wBQb/GTNIEABSAhRDVUVJAAAACH/AAAAAAAAAADEAAAIUQ1VFSQAAAAl/wAAAKTLgAAAwCQsCJENVRUkAAAazf8AAAAAAAAwQQURGUgEz8gE0PvgGswQqaAIAAOaDx4E=
/DBoAAAAAAAAAP/wBQb/GV3agABSAhRDVUVJAAAACX/AAAAAAAAAADEAAAIUQ1VFSQAAAAp/wAAAKTLgAAAwCgsCJENVRUkAAAazf8AAAAAAAAwQQURGUgEz8gE0PvgGswQqaAIAAIFPWbg=
/DBoAAAAAAAAAP/wBQb/GYhs8ABSAhRDVUVJAAAACn/AAAAAAAAAADEAAAIUQ1VFSQAAAAt/wAAAKTLgAAAwCwsCJENVRUkAAAazf8AAAAAAAAwQQURGUgEz8gE0PvgGswQqaAIAAIf5gGs=
/DBCAAAAAAAAAP/wBQb/GbL/YAAsAhRDVUVJAAAAC3/AAAAAAAAAADEAAAIUQ1VFSQAAAAx/wAAABX5AAAAwAAA/8K26
/DBYAAAAAAAAAP/wBQb/Gbh9oABCAhRDVUVJAAAADH/AAAAAAAAAADEAAAIUQ1VFSQAABrN/wAAAAAAAAAAjAQECFENVRUkAAAazf8AAAAAAAAAANQEB5cJKiQ==" />
	<input type="submit" value="2020-12-08 17h40 FTV2" />
</form>
<br/>
<form method="post">
        <input type="hidden" name="base64" value="/DBoAAAAAAAAAP/wBQb+/vMSIgBSAhRDVUVJIgAFgn/AAAHsIfAAACIBAQIUQ1VFSTACJtZ/wAAABEjgAAAwAA4CJENVRUkCAAWCf8AAAewh8AwQQURGUgEz9gE0PvgFggV32AIAAIOt8fk=
/DCGAAAAAAAAAP/wBQb+/vdbAgBwAhxDVUVJNAAFgn/AAAHn2RAICAAAAAAAAAWCNAEBAhRDVUVJMAIm13/AAAAUmXAAADABDgIkQ1VFSQIABYJ/wAAB7CHwDBBBREZSATP2ATQ++AWCBXfYAgAAAhRDVUVJMAIm1n/AAAAESOAAADEADg0CS7E=
/DBoAAAAAAAAAP/wBQb+/wydMgBSAhRDVUVJMAIm2H/AAAApMuAAADACDgIkQ1VFSQIABYJ/wAAB7CHwDBBBREZSATP2ATQ++AWCBXfYAgAAAhRDVUVJMAIm13/AAAAUmXAAADEBDknJe00=
/DBoAAAAAAAAAP/wBQb+/zZ40gBSAhRDVUVJMAIm2X/AAAAiVRAAADADDgIkQ1VFSQIABYJ/wAAB7CHwDBBBREZSATP2ATQ++AWCBXfYAgAAAhRDVUVJMAIm2H/AAAApMuAAADECDl5vOn4=
/DBoAAAAAAAAAP/wBQb+/1l2ogBSAhRDVUVJMAIm2n/AAAAc1tAAADAEDgIkQ1VFSQIABYJ/wAAB7CHwDBBBREZSATP2ATQ++AWCBXfYAgAAAhRDVUVJMAIm2X/AAAAiVRAAADEDDjmcLW0=
/DBoAAAAAAAAAP/wBQb+/3b2MgBSAhRDVUVJMAIm23/AAAApMuAAADAFDgIkQ1VFSQIABYJ/wAAB7CHwDBBBREZSATP2ATQ++AWCBXfYAgAAAhRDVUVJMAIm2n/AAAAc1tAAADEEDg3A0JU=
/DBoAAAAAAAAAP/wBQb+/6DR0gBSAhRDVUVJMAIm3H/AAAAwELAAADAGDgIkQ1VFSQIABYJ/wAAB7CHwDBBBREZSATP2ATQ++AWCBXfYAgAAAhRDVUVJMAIm23/AAAApMuAAADEFDhK2h0I=
/DBoAAAAAAAAAP/wBQb+/9GLQgBSAhRDVUVJMAIm3X/AAAAjtKAAADAHDgIkQ1VFSQIABYJ/wAAB7CHwDBBBREZSATP2ATQ++AWCBXfYAgAAAhRDVUVJMAIm3H/AAAAwELAAADEGDv/I0TI=
/DBoAAAAAAAAAP/wBQb+//XoogBSAhRDVUVJMAIm3n/AAAAbd0AAADAIDgIkQ1VFSQIABYJ/wAAB7CHwDBBBREZSATP2ATQ++AWCBXfYAgAAAhRDVUVJMAIm3X/AAAAjtKAAADEHDj1tLms=
/DBoAAAAAAAAAP/wBQb/ABIIogBSAhRDVUVJMAIm33/AAAApMuAAADAJDgIkQ1VFSQIABYJ/wAAB7CHwDBBBREZSATP2ATQ++AWCBXfYAgAAAhRDVUVJMAIm3n/AAAAbd0AAADEIDugPkQE=
/DBoAAAAAAAAAP/wBQb/ADvkQgBSAhRDVUVJMAIm4H/AAAATOeAAADAKDgIkQ1VFSQIABYJ/wAAB7CHwDBBBREZSATP2ATQ++AWCBXfYAgAAAhRDVUVJMAIm33/AAAApMuAAADEJDq/L1Yw=
/DBoAAAAAAAAAP/wBQb/AE/G4gBSAhRDVUVJMAIm4X/AAAAbd0AAADALDgIkQ1VFSQIABYJ/wAAB7CHwDBBBREZSATP2ATQ++AWCBXfYAgAAAhRDVUVJMAIm4H/AAAATOeAAADEKDsZ895o=
/DBoAAAAAAAAAP/wBQb/AGvm4gBSAhRDVUVJMAIm4n/AAAAbd0AAADAMDgIkQ1VFSQIABYJ/wAAB7CHwDBBBREZSATP2ATQ++AWCBXfYAgAAAhRDVUVJMAIm4X/AAAAbd0AAADELDg35KpU=
/DBoAAAAAAAAAP/wBQb/AIgG4gBSAhRDVUVJMAIm43/AAAApMuAAADANDgIkQ1VFSQIABYJ/wAAB7CHwDBBBREZSATP2ATQ++AWCBXfYAgAAAhRDVUVJMAIm4n/AAAAbd0AAADEMDlWWEtE=
/DBoAAAAAAAAAP/wBQb/ALHiggBSAhRDVUVJMAIm5H/AAAApMuAAADAODgIkQ1VFSQIABYJ/wAAB7CHwDBBBREZSATP2ATQ++AWCBXfYAgAAAhRDVUVJMAIm43/AAAApMuAAADENDhuD61Y=
/DBCAAAAAAAAAP/wBQb/ANsVYgAsAhRDVUVJMAIm1n/AAAAEHrAAADAAAAIUQ1VFSTACJuR/wAAAKTLgAAAxDg6ohhok
/DBgAAAAAAAAAP/wBQb/AN80EgBKAhxDVUVJNAAFgn/AAAHn2RAICAAAAAAAAAWCNQEBAhRDVUVJIgAFgn/AAAHsIfAAACMBAQIUQ1VFSTACJtZ/wAAABB6wAAAxAAC9+aDD
/DBoAAAAAAAAAP/wBQb/B2nZcgBSAhRDVUVJIgAFoH/AAAHvl+AAACIBAQIUQ1VFSTACMo1/wAAABEjgAAAwAA0CJENVRUkCAAWgf8AAAe+X4AwQQURGUgEz9gE0PvgFoAWBsAIAALhxBqQ=
/DCGAAAAAAAAAP/wBQb/B24iUgBwAhxDVUVJNAAFoH/AAAHrTwAICAAAAAAAAAWgNAEBAhRDVUVJMAIyjn/AAAApMuAAADABDQIkQ1VFSQIABaB/wAAB75fgDBBBREZSATP2ATQ++AWgBYGwAgAAAhRDVUVJMAIyjX/AAAAESOAAADEADff8AqY=
/DBoAAAAAAAAAP/wBQb/B5f98gBSAhRDVUVJMAIyj3/AAAAbd0AAADACDQIkQ1VFSQIABaB/wAAB75fgDBBBREZSATP2ATQ++AWgBYGwAgAAAhRDVUVJMAIyjn/AAAApMuAAADEBDahy0Ec=
/DBoAAAAAAAAAP/wBQb/B7Qd8gBSAhRDVUVJMAIykH/AAAAbd0AAADADDQIkQ1VFSQIABaB/wAAB75fgDBBBREZSATP2ATQ++AWgBYGwAgAAAhRDVUVJMAIyj3/AAAAbd0AAADECDbBeNQU=
/DBoAAAAAAAAAP/wBQb/B9A98gBSAhRDVUVJMAIykX/AAAAbd0AAADAEDQIkQ1VFSQIABaB/wAAB75fgDBBBREZSATP2ATQ++AWgBYGwAgAAAhRDVUVJMAIykH/AAAAbd0AAADEDDYf9FjI=
/DBoAAAAAAAAAP/wBQb/B+xd8gBSAhRDVUVJMAIykn/AAAAaF7AAADAFDQIkQ1VFSQIABaB/wAAB75fgDBBBREZSATP2ATQ++AWgBYGwAgAAAhRDVUVJMAIykX/AAAAbd0AAADEEDVI8JAQ=
/DBoAAAAAAAAAP/wBQb/CAceYgBSAhRDVUVJMAIyk3/AAAA9zFAAADAGDQIkQ1VFSQIABaB/wAAB75fgDBBBREZSATP2ATQ++AWgBYGwAgAAAhRDVUVJMAIykn/AAAAaF7AAADEFDYHdODU=
/DBoAAAAAAAAAP/wBQb/CEWTcgBSAhRDVUVJMAIylH/AAAAUmXAAADAHDQIkQ1VFSQIABaB/wAAB75fgDBBBREZSATP2ATQ++AWgBYGwAgAAAhRDVUVJMAIyk3/AAAA9zFAAADEGDbgUYIY=
/DBoAAAAAAAAAP/wBQb/CFrjsgBSAhRDVUVJMAIylX/AAAAbd0AAADAIDQIkQ1VFSQIABaB/wAAB75fgDBBBREZSATP2ATQ++AWgBYGwAgAAAhRDVUVJMAIylH/AAAAUmXAAADEHDYuo0ho=
/DBoAAAAAAAAAP/wBQb/CHb1ogBSAhRDVUVJMAIyln/AAAAbd0AAADAJDQIkQ1VFSQIABaB/wAAB75fgDBBBREZSATP2ATQ++AWgBYGwAgAAAhRDVUVJMAIylX/AAAAbd0AAADEIDZIEmHk=
/DBoAAAAAAAAAP/wBQb/CJMVogBSAhRDVUVJMAIyl3/AAAApMuAAADAKDQIkQ1VFSQIABaB/wAAB75fgDBBBREZSATP2ATQ++AWgBYGwAgAAAhRDVUVJMAIyln/AAAAbd0AAADEJDTYmDs8=
/DBoAAAAAAAAAP/wBQb/CLzxQgBSAhRDVUVJMAIymH/AAABSZcAAADALDQIkQ1VFSQIABaB/wAAB75fgDBBBREZSATP2ATQ++AWgBYGwAgAAAhRDVUVJMAIyl3/AAAApMuAAADEKDaH2WPQ=
/DBoAAAAAAAAAP/wBQb/CQ//wgBSAhRDVUVJMAIymX/AAAAbd0AAADAMDQIkQ1VFSQIABaB/wAAB75fgDBBBREZSATP2ATQ++AWgBYGwAgAAAhRDVUVJMAIymH/AAABSZcAAADELDV0RfmA=
/DBoAAAAAAAAAP/wBQb/CSwfwgBSAhRDVUVJMAIymn/AAAApMuAAADANDQIkQ1VFSQIABaB/wAAB75fgDBBBREZSATP2ATQ++AWgBYGwAgAAAhRDVUVJMAIymX/AAAAbd0AAADEMDSBEYHI=
/DBCAAAAAAAAAP/wBQb/CVVSogAsAhRDVUVJMAIyjX/AAAAEHrAAADAAAAIUQ1VFSTACMpp/wAAAKTLgAAAxDQ2Ljd0y
/DBgAAAAAAAAAP/wBQb/CVlxUgBKAhxDVUVJNAAFoH/AAAHrTwAICAAAAAAAAAWgNQEBAhRDVUVJIgAFoH/AAAHvl+AAACMBAQIUQ1VFSTACMo1/wAAABB6wAAAxAAC75Iz6
/DBoAAAAAAAAAP/wBQb/FlDoIgBSAhRDVUVJIgAF63/AAAIB/tAAACIBAQIUQ1VFSTACT95/wAAABEjgAAAwABICJENVRUkCAAXrf8AAAgH+0AwQQURGUgEz9gE0PvgF6wW2CAIAAPei/4M=
/DCGAAAAAAAAAP/wBQb/FlUxAgBwAhxDVUVJNAAF63/AAAH9tfAICAAAAAAAAAXrNAEBAhRDVUVJMAJP33/AAAANu6AAADABEgIkQ1VFSQIABet/wAACAf7QDBBBREZSATP2ATQ++AXrBbYIAgAAAhRDVUVJMAJP3n/AAAAESOAAADEAEosXILE=
/DBoAAAAAAAAAP/wBQb/FmOVYgBSAhRDVUVJMAJP4H/AAAAUmXAAADACEgIkQ1VFSQIABet/wAACAf7QDBBBREZSATP2ATQ++AXrBbYIAgAAAhRDVUVJMAJP33/AAAANu6AAADEBEk+V0fA=
/DBoAAAAAAAAAP/wBQb/FnjXkgBSAhRDVUVJMAJP4X/AAAAbd0AAADADEgIkQ1VFSQIABet/wAACAf7QDBBBREZSATP2ATQ++AXrBbYIAgAAAhRDVUVJMAJP4H/AAAAUmXAAADECEp8GW2c=
/DBoAAAAAAAAAP/wBQb/FpT3kgBSAhRDVUVJMAJP4n/AAAAbd0AAADAEEgIkQ1VFSQIABet/wAACAf7QDBBBREZSATP2ATQ++AXrBbYIAgAAAhRDVUVJMAJP4X/AAAAbd0AAADEDEuwcsUg=
/DBoAAAAAAAAAP/wBQb/FrEXkgBSAhRDVUVJMAJP43/AAAAbd0AAADAFEgIkQ1VFSQIABet/wAACAf7QDBBBREZSATP2ATQ++AXrBbYIAgAAAhRDVUVJMAJP4n/AAAAbd0AAADEEEr6iaCo=
/DBoAAAAAAAAAP/wBQb/Fs03kgBSAhRDVUVJMAJP5H/AAAAbd0AAADAGEgIkQ1VFSQIABet/wAACAf7QDBBBREZSATP2ATQ++AXrBbYIAgAAAhRDVUVJMAJP43/AAAAbd0AAADEFEp2SdSk=
/DBoAAAAAAAAAP/wBQb/FulXkgBSAhRDVUVJMAJP5X/AAAAUmXAAADAHEgIkQ1VFSQIABet/wAACAf7QDBBBREZSATP2ATQ++AXrBbYIAgAAAhRDVUVJMAJP5H/AAAAbd0AAADEGEkO0jIc=
/DBoAAAAAAAAAP/wBQb/Fv6ZwgBSAhRDVUVJMAJP5n/AAAApMuAAADAIEgIkQ1VFSQIABet/wAACAf7QDBBBREZSATP2ATQ++AXrBbYIAgAAAhRDVUVJMAJP5X/AAAAUmXAAADEHEkR6VAQ=
/DBoAAAAAAAAAP/wBQb/Fyh1YgBSAhRDVUVJMAJP53/AAAAbd0AAADAJEgIkQ1VFSQIABet/wAACAf7QDBBBREZSATP2ATQ++AXrBbYIAgAAAhRDVUVJMAJP5n/AAAApMuAAADEIEj7vnHs=
/DBoAAAAAAAAAP/wBQb/F0SVYgBSAhRDVUVJMAJP6H/AAAApMuAAADAKEgIkQ1VFSQIABet/wAACAf7QDBBBREZSATP2ATQ++AXrBbYIAgAAAhRDVUVJMAJP53/AAAAbd0AAADEJEqxV0AY=
/DBoAAAAAAAAAP/wBQb/F25xAgBSAhRDVUVJMAJP6X/AAAAUmXAAADALEgIkQ1VFSQIABet/wAACAf7QDBBBREZSATP2ATQ++AXrBbYIAgAAAhRDVUVJMAJP6H/AAAApMuAAADEKEq3kXgo=
/DBoAAAAAAAAAP/wBQb/F4PBQgBSAhRDVUVJMAJP6n/AAAAbd0AAADAMEgIkQ1VFSQIABet/wAACAf7QDBBBREZSATP2ATQ++AXrBbYIAgAAAhRDVUVJMAJP6X/AAAAUmXAAADELEvlNOWo=
/DBoAAAAAAAAAP/wBQb/F5/TMgBSAhRDVUVJMAJP63/AAAApMuAAADANEgIkQ1VFSQIABet/wAACAf7QDBBBREZSATP2ATQ++AXrBbYIAgAAAhRDVUVJMAJP6n/AAAAbd0AAADEMEhtRdbg=
/DBoAAAAAAAAAP/wBQb/F8mu0gBSAhRDVUVJMAJP7H/AAAApMuAAADAOEgIkQ1VFSQIABet/wAACAf7QDBBBREZSATP2ATQ++AXrBbYIAgAAAhRDVUVJMAJP63/AAAApMuAAADENEr54BQ8=
/DBoAAAAAAAAAP/wBQb/F/OKcgBSAhRDVUVJMAJP7X/AAAAUmXAAADAPEgIkQ1VFSQIABet/wAACAf7QDBBBREZSATP2ATQ++AXrBbYIAgAAAhRDVUVJMAJP7H/AAAApMuAAADEOElYuMbE=
/DBoAAAAAAAAAP/wBQb/GAjMogBSAhRDVUVJMAJP7n/AAAAiVRAAADAQEgIkQ1VFSQIABet/wAACAf7QDBBBREZSATP2ATQ++AXrBbYIAgAAAhRDVUVJMAJP7X/AAAAUmXAAADEPEm5jhHM=
/DBoAAAAAAAAAP/wBQb/GCvKcgBSAhRDVUVJMAJP73/AAAANu6AAADAREgIkQ1VFSQIABet/wAACAf7QDBBBREZSATP2ATQ++AXrBbYIAgAAAhRDVUVJMAJP7n/AAAAiVRAAADEQEjzUaas=
/DBoAAAAAAAAAP/wBQb/GDou0gBSAhRDVUVJMAJP8H/AAAAUmXAAADASEgIkQ1VFSQIABet/wAACAf7QDBBBREZSATP2ATQ++AXrBbYIAgAAAhRDVUVJMAJP73/AAAANu6AAADEREqNpOOE=
/DBCAAAAAAAAAP/wBQb/GE7IQgAsAhRDVUVJMAJP3n/AAAAEHrAAADAAAAIUQ1VFSTACT/B/wAAAFJlwAAAxEhJLGo/7
/DB+AAAAAAAAAP/wBQb/GFLm8gBoAhxDVUVJNAAF63/AAAH9tfAICAAAAAAAAAXrNQEBAhRDVUVJIgAF63/AAAIB/tAAACMBAQIUQ1VFSTACT95/wAAABB6wAAAxAAACHENVRUkQWHTFf8AAIBk5YAgIOF+3xQAAAAARAAB4nBL9
/DBoAAAAAAAAAP/wBQb/GPeycgBSAhRDVUVJIgAF+n/AAAGEa/AAACIBAQIUQ1VFSTACVbd/wAAABwgAAAAwAA8CJENVRUkCAAX6f8AAAYRr8AwQQURGUgEz9gE0PvgF+gRQ2AIAAO6akww=
/DCGAAAAAAAAAP/wBQb/GP7IggBwAhxDVUVJNAAF+n/AAAF9Y/AICAAAAAAAAAX6NAEBAhRDVUVJMAJVuH/AAAAg9YAAADABDwIkQ1VFSQIABfp/wAABhGvwDBBBREZSATP2ATQ++AX6BFDYAgAAAhRDVUVJMAJVt3/AAAAHCAAAADEAD2loy6Q=
/DBoAAAAAAAAAP/wBQb/GSBYsgBSAhRDVUVJMAJVuX/AAAAbd0AAADACDwIkQ1VFSQIABfp/wAABhGvwDBBBREZSATP2ATQ++AX6BFDYAgAAAhRDVUVJMAJVuH/AAAAg9YAAADEBD7JllEs=
/DBoAAAAAAAAAP/wBQb/GTx4sgBSAhRDVUVJMAJVun/AAAANu6AAADADDwIkQ1VFSQIABfp/wAABhGvwDBBBREZSATP2ATQ++AX6BFDYAgAAAhRDVUVJMAJVuX/AAAAbd0AAADECD+D0MWQ=
/DBoAAAAAAAAAP/wBQb/GUrdEgBSAhRDVUVJMAJVu3/AAAAbd0AAADAEDwIkQ1VFSQIABfp/wAABhGvwDBBBREZSATP2ATQ++AX6BFDYAgAAAhRDVUVJMAJVun/AAAANu6AAADEDD260j3A=
/DBoAAAAAAAAAP/wBQb/GWb9EgBSAhRDVUVJMAJVvH/AAAAbd0AAADAFDwIkQ1VFSQIABfp/wAABhGvwDBBBREZSATP2ATQ++AX6BFDYAgAAAhRDVUVJMAJVu3/AAAAbd0AAADEED7qGaOI=
/DBoAAAAAAAAAP/wBQb/GYMdEgBSAhRDVUVJMAJVvX/AAAApMuAAADAGDwIkQ1VFSQIABfp/wAABhGvwDBBBREZSATP2ATQ++AX6BFDYAgAAAhRDVUVJMAJVvH/AAAAbd0AAADEFD7F2gJk=
/DBoAAAAAAAAAP/wBQb/Gaz4sgBSAhRDVUVJMAJVvn/AAAAUmXAAADAHDwIkQ1VFSQIABfp/wAABhGvwDBBBREZSATP2ATQ++AX6BFDYAgAAAhRDVUVJMAJVvX/AAAApMuAAADEGD+a5NCc=
/DBoAAAAAAAAAP/wBQb/GcI64gBSAhRDVUVJMAJVv3/AAAAbd0AAADAIDwIkQ1VFSQIABfp/wAABhGvwDBBBREZSATP2ATQ++AX6BFDYAgAAAhRDVUVJMAJVvn/AAAAUmXAAADEHD+Usn1Q=
/DBoAAAAAAAAAP/wBQb/Gd5a4gBSAhRDVUVJMAJVwH/AAAAXWJAAADAJDwIkQ1VFSQIABfp/wAABhGvwDBBBREZSATP2ATQ++AX6BFDYAgAAAhRDVUVJMAJVv3/AAAAbd0AAADEID090FUU=
/DBoAAAAAAAAAP/wBQb/GfZcMgBSAhRDVUVJMAJVwX/AAAAUmXAAADAKDwIkQ1VFSQIABfp/wAABhGvwDBBBREZSATP2ATQ++AX6BFDYAgAAAhRDVUVJMAJVwH/AAAAXWJAAADEJD1+iTtM=
/DBoAAAAAAAAAP/wBQb/GgueYgBSAhRDVUVJMAJVwn/AAAAUmXAAADALDwIkQ1VFSQIABfp/wAABhGvwDBBBREZSATP2ATQ++AX6BFDYAgAAAhRDVUVJMAJVwX/AAAAUmXAAADEKD3yvnhE=
/DBoAAAAAAAAAP/wBQb/GiDgkgBSAhRDVUVJMAJVw3/AAAAXWJAAADAMDwIkQ1VFSQIABfp/wAABhGvwDBBBREZSATP2ATQ++AX6BFDYAgAAAhRDVUVJMAJVwn/AAAAUmXAAADELD7DidHk=
/DBoAAAAAAAAAP/wBQb/Gjjh4gBSAhRDVUVJMAJVxH/AAAAUmXAAADANDwIkQ1VFSQIABfp/wAABhGvwDBBBREZSATP2ATQ++AX6BFDYAgAAAhRDVUVJMAJVw3/AAAAXWJAAADEMD8wiKUg=
/DBoAAAAAAAAAP/wBQb/Gk4kEgBSAhRDVUVJMAJVxX/AAAAUmXAAADAODwIkQ1VFSQIABfp/wAABhGvwDBBBREZSATP2ATQ++AX6BFDYAgAAAhRDVUVJMAJVxH/AAAAUmXAAADEND5WKSFA=
/DBoAAAAAAAAAP/wBQb/GmNmQgBSAhRDVUVJMAJVxn/AAAAUmXAAADAPDwIkQ1VFSQIABfp/wAABhGvwDBBBREZSATP2ATQ++AX6BFDYAgAAAhRDVUVJMAJVxX/AAAAUmXAAADEOD17snUw=
/DBCAAAAAAAAAP/wBQb/Gnf/sgAsAhRDVUVJMAJVt3/AAAAEHrAAADAAAAIUQ1VFSTACVcZ/wAAAFJlwAAAxDw+aPak7
/DBgAAAAAAAAAP/wBQb/GnweYgBKAhxDVUVJNAAF+n/AAAF9Y/AICAAAAAAAAAX6NQEBAhRDVUVJIgAF+n/AAAGEa/AAACMBAQIUQ1VFSTACVbd/wAAABB6wAAAxAAArgviy
/DBoAAAAAAAAAP/wBQb/Is/Z0gBSAhRDVUVJIgAGSn/AAAD2enAAACIBAQIUQ1VFSTAAPux/wAAABEjgAAAwAAgCJENVRUkCAAZKf8AAAPZ6cAwQQURGUgEz9gE0PvgGSgK9GAIAAOfHMv4=
/DCGAAAAAAAAAP/wBQb/ItQUogBwAhxDVUVJNAAGSn/AAADyMZAICAAAAAAAAAZKNAEBAhRDVUVJMAA+7X/AAAAbd0AAADABCAIkQ1VFSQIABkp/wAAA9npwDBBBREZSATP2ATQ++AZKAr0YAgAAAhRDVUVJMAA+7H/AAAAESOAAADEACNySBqE=
/DBoAAAAAAAAAP/wBQb/IvA0ogBSAhRDVUVJMAJ08n/AAAApMuAAADACCAIkQ1VFSQIABkp/wAAA9npwDBBBREZSATP2ATQ++AZKAr0YAgAAAhRDVUVJMAA+7X/AAAAbd0AAADEBCEgJk5A=
/DBoAAAAAAAAAP/wBQb/IxoQQgBSAhRDVUVJMAJ083/AAAAbd0AAADADCAIkQ1VFSQIABkp/wAAA9npwDBBBREZSATP2ATQ++AZKAr0YAgAAAhRDVUVJMAJ08n/AAAApMuAAADECCEjtiZU=
/DBoAAAAAAAAAP/wBQb/IzYwQgBSAhRDVUVJMAJ09H/AAAAbd0AAADAECAIkQ1VFSQIABkp/wAAA9npwDBBBREZSATP2ATQ++AZKAr0YAgAAAhRDVUVJMAJ083/AAAAbd0AAADEDCIlfJus=
/DBoAAAAAAAAAP/wBQb/I1JeUgBSAhRDVUVJMAJ09X/AAAAbd0AAADAFCAIkQ1VFSQIABkp/wAAA9npwDBBBREZSATP2ATQ++AZKAr0YAgAAAhRDVUVJMAJ09H/AAAAbd0AAADEECCm6414=
/DBoAAAAAAAAAP/wBQb/I25wQgBSAhRDVUVJMAJ09n/AAAANu6AAADAGCAIkQ1VFSQIABkp/wAAA9npwDBBBREZSATP2ATQ++AZKAr0YAgAAAhRDVUVJMAJ09X/AAAAbd0AAADEFCNJaSFg=
/DBoAAAAAAAAAP/wBQb/I3zisgBSAhRDVUVJMAJ093/AAAApMuAAADAHCAIkQ1VFSQIABkp/wAAA9npwDBBBREZSATP2ATQ++AZKAr0YAgAAAhRDVUVJMAJ09n/AAAANu6AAADEGCLVqlKs=
/DBoAAAAAAAAAP/wBQb/I6awQgBSAhRDVUVJMAJ0+H/AAAAbd0AAADAICAIkQ1VFSQIABkp/wAAA9npwDBBBREZSATP2ATQ++AZKAr0YAgAAAhRDVUVJMAJ093/AAAApMuAAADEHCED5rGM=
/DBCAAAAAAAAAP/wBQb/I8InggAsAhRDVUVJMAA+7H/AAAAEHrAAADAAAAIUQ1VFSTACdPh/wAAAG3dAAAAxCAjn1gRs
/DBgAAAAAAAAAP/wBQb/I8ZGMgBKAhxDVUVJNAAGSn/AAADyMZAICAAAAAAAAAZKNQEBAhRDVUVJIgAGSn/AAAD2enAAACMBAQIUQ1VFSTAAPux/wAAABB6wAAAxAAA0G/Yq
/DA0AAAAAAAAAP/wBQb/KfAhcgAeAhxDVUVJEAMK3n/AABEXsJAICDii5F4AAAAAEAAA2yX1iQ==
/DBoAAAAAAAAAP/wBQb/LEZkIgBSAhRDVUVJIgAGaH/AAAD+AQAAACIBAQIUQ1VFSTAAQBl/wAAABwgAAAAwAAkCJENVRUkCAAZof8AAAP4BAAwQQURGUgEz9gE0PvgGaALSgAIAAHRfVWI=
/DCGAAAAAAAAAP/wBQb/LE1sIgBwAhxDVUVJNAAGaH/AAAD2+QAICAAAAAAAAAZoNAEBAhRDVUVJMAKAqn/AAAAg9YAAADABCQIkQ1VFSQIABmh/wAAA/gEADBBBREZSATP2ATQ++AZoAtKAAgAAAhRDVUVJMABAGX/AAAAHCAAAADEACeGhQWA=
/DBoAAAAAAAAAP/wBQb/LG8KYgBSAhRDVUVJMAKAq3/AAAANu6AAADACCQIkQ1VFSQIABmh/wAAA/gEADBBBREZSATP2ATQ++AZoAtKAAgAAAhRDVUVJMAKAqn/AAAAg9YAAADEBCSbARrw=
/DBoAAAAAAAAAP/wBQb/LH1uwgBSAhRDVUVJMAKArH/AAAAg9YAAADADCQIkQ1VFSQIABmh/wAAA/gEADBBBREZSATP2ATQ++AZoAtKAAgAAAhRDVUVJMAKAq3/AAAANu6AAADECCXb0tB0=
/DBoAAAAAAAAAP/wBQb/LJ8NAgBSAhRDVUVJMAKArX/AAAAbd0AAADAECQIkQ1VFSQIABmh/wAAA/gEADBBBREZSATP2ATQ++AZoAtKAAgAAAhRDVUVJMAKArH/AAAAg9YAAADEDCcTXX9c=
/DBoAAAAAAAAAP/wBQb/LLstAgBSAhRDVUVJMAKArn/AAAAUmXAAADAFCQIkQ1VFSQIABmh/wAAA/gEADBBBREZSATP2ATQ++AZoAtKAAgAAAhRDVUVJMAKArX/AAAAbd0AAADEECScVy68=
/DBoAAAAAAAAAP/wBQb/LNBvMgBSAhRDVUVJMAKAr3/AAAAbd0AAADAGCQIkQ1VFSQIABmh/wAAA/gEADBBBREZSATP2ATQ++AZoAtKAAgAAAhRDVUVJMAKArn/AAAAUmXAAADEFCWfz/to=
/DBoAAAAAAAAAP/wBQb/LOyPMgBSAhRDVUVJMAKAsH/AAAApMuAAADAHCQIkQ1VFSQIABmh/wAAA/gEADBBBREZSATP2ATQ++AZoAtKAAgAAAhRDVUVJMAKAr3/AAAAbd0AAADEGCbShuE8=
/DBoAAAAAAAAAP/wBQb/LRZq0gBSAhRDVUVJMAKAsX/AAAANu6AAADAICQIkQ1VFSQIABmh/wAAA/gEADBBBREZSATP2ATQ++AZoAtKAAgAAAhRDVUVJMAKAsH/AAAApMuAAADEHCXsPDdg=
/DBoAAAAAAAAAP/wBQb/LSTPMgBSAhRDVUVJMAKAsn/AAAAbd0AAADAJCQIkQ1VFSQIABmh/wAAA/gEADBBBREZSATP2ATQ++AZoAtKAAgAAAhRDVUVJMAKAsX/AAAANu6AAADEICegJCbU=
/DBCAAAAAAAAAP/wBQb/LUBGcgAsAhRDVUVJMABAGX/AAAAEHrAAADAAAAIUQ1VFSTACgLJ/wAAAG3dAAAAxCQnJ7mtA
/DBgAAAAAAAAAP/wBQb/LURlIgBKAhxDVUVJNAAGaH/AAAD2+QAICAAAAAAAAAZoNQEBAhRDVUVJIgAGaH/AAAD+AQAAACMBAQIUQ1VFSTAAQBl/wAAABB6wAAAxAABVQcWA
/DA0AAAAAAAAAP/wBQb/Owe14gAeAhxDVUVJEAMK3n/AABEXsJAICDii5F4AAAAAEQAATzBmmg==
/DBoAAAAAAAAAP/wBQb/PQID8ABSAhRDVUVJIgAHEn/AAAH/P7AAACIBAQIUQ1VFSTACwxp/wAAABEjgAAAwABICJENVRUkCAAcSf8AAAf8/sAwQQURGUgEz9gE0PvgHEgWuOAIAABT3/x0=
/DCGAAAAAAAAAP/wBQb/PQZM0gBwAhxDVUVJNAAHEn/AAAH69tAICAAAAAAAAAcSNAEBAhRDVUVJMALDG3/AAAAUmXAAADABEgIkQ1VFSQIABxJ/wAAB/z+wDBBBREZSATP2ATQ++AcSBa44AgAAAhRDVUVJMALDGn/AAAAESOAAADEAEkXmE0o=
/DBoAAAAAAAAAP/wBQb/PRudEgBSAhRDVUVJMALDHH/AAAAUmXAAADACEgIkQ1VFSQIABxJ/wAAB/z+wDBBBREZSATP2ATQ++AcSBa44AgAAAhRDVUVJMALDG3/AAAAUmXAAADEBEvkyoJw=
/DBoAAAAAAAAAP/wBQb/PTDRMgBSAhRDVUVJMALDHX/AAAAbd0AAADADEgIkQ1VFSQIABxJ/wAAB/z+wDBBBREZSATP2ATQ++AcSBa44AgAAAhRDVUVJMALDHH/AAAAUmXAAADECEsd87n4=
/DBoAAAAAAAAAP/wBQb/PUzxMgBSAhRDVUVJMALDHn/AAAAiVRAAADAEEgIkQ1VFSQIABxJ/wAAB/z+wDBBBREZSATP2ATQ++AcSBa44AgAAAhRDVUVJMALDHX/AAAAbd0AAADEDEr4mhdo=
/DBoAAAAAAAAAP/wBQb/PW/vAgBSAhRDVUVJMALDH3/AAAAeNmAAADAFEgIkQ1VFSQIABxJ/wAAB/z+wDBBBREZSATP2ATQ++AcSBa44AgAAAhRDVUVJMALDHn/AAAAiVRAAADEEEvYQ3Ww=
/DBoAAAAAAAAAP/wBQb/PY7OIgBSAhRDVUVJMALDIH/AAAAbd0AAADAGEgIkQ1VFSQIABxJ/wAAB/z+wDBBBREZSATP2ATQ++AcSBa44AgAAAhRDVUVJMALDH3/AAAAeNmAAADEFElVP+OQ=
/DBoAAAAAAAAAP/wBQb/ParuIgBSAhRDVUVJMALDIX/AAAAXWJAAADAHEgIkQ1VFSQIABxJ/wAAB/z+wDBBBREZSATP2ATQ++AcSBa44AgAAAhRDVUVJMALDIH/AAAAbd0AAADEGEiAgyV4=
/DBoAAAAAAAAAP/wBQb/PcLvcgBSAhRDVUVJMALDIn/AAAAbd0AAADAIEgIkQ1VFSQIABxJ/wAAB/z+wDBBBREZSATP2ATQ++AcSBa44AgAAAhRDVUVJMALDIX/AAAAXWJAAADEHEiqY0kE=
/DBoAAAAAAAAAP/wBQb/Pd8PcgBSAhRDVUVJMALDI3/AAAAbd0AAADAJEgIkQ1VFSQIABxJ/wAAB/z+wDBBBREZSATP2ATQ++AcSBa44AgAAAhRDVUVJMALDIn/AAAAbd0AAADEIEoEEsdk=
/DBoAAAAAAAAAP/wBQb/PfsvcgBSAhRDVUVJMALDJH/AAAAbd0AAADAKEgIkQ1VFSQIABxJ/wAAB/z+wDBBBREZSATP2ATQ++AcSBa44AgAAAhRDVUVJMALDI3/AAAAbd0AAADEJEqJCvtY=
/DBoAAAAAAAAAP/wBQb/PhdPcgBSAhRDVUVJMALDJX/AAAATOeAAADALEgIkQ1VFSQIABxJ/wAAB/z+wDBBBREZSATP2ATQ++AcSBa44AgAAAhRDVUVJMALDJH/AAAAbd0AAADEKEiZKS9o=
/DBoAAAAAAAAAP/wBQb/PisyEgBSAhRDVUVJMALDJn/AAAAjtKAAADAMEgIkQ1VFSQIABxJ/wAAB/z+wDBBBREZSATP2ATQ++AcSBa44AgAAAhRDVUVJMALDJX/AAAATOeAAADELEtISWFg=
/DBoAAAAAAAAAP/wBQb/Pk+PcgBSAhRDVUVJMALDJ3/AAAApMuAAADANEgIkQ1VFSQIABxJ/wAAB/z+wDBBBREZSATP2ATQ++AcSBa44AgAAAhRDVUVJMALDJn/AAAAjtKAAADEMEqRLgsc=" />
	<input type="submit" value="2020-12-08 17h40 M6" />
</form>
<br/>
<form method="post">
        <input type="hidden" name="base64" value="" />
	<input type="submit" value="Empty" />
</form>
<br/>



<?php

// Display Graphical Timeline

echo "<h1>Graphical Events Timeline</h1>\n";
$start = null;
$timeline = array();
$types = array();
$eventIds = array();
$maxTime = 0;
foreach ($json as $b64 => $dataJson) {
	$data = json_decode($dataJson);
	if ($start === null)
		$start = $data->splice_command->pts_time;
	foreach ($data->splice_descriptors as $descriptor) {
		$item = array(
			'start' => sprintf("%.03f", ($data->splice_command->pts_time - $start) / 90000),
			'duration' => $descriptor->segmentation_duration_flag ? $descriptor->segmentation_duration_text : 0,
			'json' => json_encode($data, JSON_PRETTY_PRINT),
			'first' => (bool)(!in_array($descriptor->segmentation_event_id.$descriptor->segment_type_text, $eventIds))
		);
		$eventIds[] = $descriptor->segmentation_event_id.$descriptor->segment_type_text;
		if (preg_match("#\(0(x.*)\)#", $descriptor->segment_type_text, $m)) {
			$types[$m[1]] = $descriptor->segment_type_text;
		}
		$timeline[$m[1]][] = $item;
		$maxTime = max($maxTime, $item['start'] + $item['duration']);
	}
}

// Vertical
/*
echo "<h2>Vertical</h2>\n";
$left = 10;
$max = 0;
$div = 10;
$width = 10;
echo '<div class="rel" style="height:'.($maxTime/$div).'em;">';
ksort($types);
foreach ($types as $type => $text) {
	echo '<div id="descTitle" class="abs '.$type.'" style="left:'.($left).'em;width:'.$width.'em;">'.$text.'</div>';
	foreach ($timeline[$type] as $desc) {
		if ($desc['first']) {
			echo '<div id="desc" class="abs '.$type.'" style="left:'.($left).'em; top:'.(10 + $desc['start']/$div).'em;height:'.max($desc['duration']/$div,0.2).'em;width:'.$width.'em;">'.$type.'</div>';
		}
		else {
			echo '<div id="desc" class="abs '.$type.' dupl" style="left:'.($left).'em; top:'.(10 + $desc['start']/$div).'em;height:'.max($desc['duration']/$div,0.2).'em;width:'.$width.'em;">'.$type.'</div>';	
		}
		$max = max($max,$desc['start']+$desc['duration']);
	}

	$left += $width;
}
for ($i=0; $i<=$max; $i+=300) {
	echo '<div id="time" class="abs" style="top:'.(10+$i/$div).'em;">+'.$i.' sec.</div>';
}
echo '</div>';
echo '<div style="clear:both;">&nbsp;</div>';
*/

// Horizontal
echo "<h2>Horizontal</h2>\n";
echo '<div class="rel" style="height:'.(count($types)*5).'em;">';
$top = 0;
$max = 0;
$div = 20;
ksort($types);
foreach ($types as $type => $text) {
	echo '<div id="descTitle" class="abs '.$type.'" style="top:'.($top).'em;">'.$text.'</div>';
	foreach ($timeline[$type] as $desc) {
		if ($desc['first']) {
			echo '<div id="desc" class="abs '.$type.'" style="top:'.($top).'em; left:'.(10 + $desc['start']/$div).'em;width:'.max($desc['duration']/$div,0.2).'em;">'.$type.'</div>';
		}
		else {
			echo '<div id="desc" class="abs '.$type.' dupl" style="top:'.($top).'em; left:'.(10 + $desc['start']/$div).'em;width:'.max($desc['duration']/$div,0.2).'em;">'.$type.'</div>';	
		}
		$max = max($max,$desc['start']+$desc['duration']);
	}
	$top += 5;
}
for ($i=0; $i<=$max; $i+=300) {
	$diffStart = $i;
	echo '<div id="time" class="abs" style="left:'.(10+$i/$div).'em;">'.sprintf("%02d:%02d:%02d.%03d", $diffStart / 3600, ($diffStart % 3600) / 60, $diffStart % 60, ($diffStart*1000) % 1000).'</div>';
}
echo '</div>';

// Display Timeline
echo "<h1>Events Timeline</h1>\n";
$start = null;
echo "<pre>\n";
$pattern = "%-20s%-15s%-15s%-20s%-25s%-10s\n";
echo sprintf($pattern, "Time", "Program", "AdServer", "Break", "Placement Opportunity", "Advertisement");
echo sprintf($pattern, "----", "-------", "--------", "-----", "---------------------", "-------------");
foreach ($arBase64 as $b64) {
	if (!isset($json[$b64])) {
		if (isset($error[$b64]))
			echo "Error on ".$b64."\n";
		else
			echo "Not processed: ".$b64."\n";
	}
	else {
		//echo "OK: ".$b64."\n";
		$data = json_decode($json[$b64]);
		if ($start === null) {
			$start = $data->splice_command->pts_time;
		}
		$out = array("Time" => $data->splice_command->pts_time_text, "Program" => "", "AdServer" => "", "Break" => "", "Placement Opportunity" => "", "Advertisement" => "");
		$diffStart = ($data->splice_command->pts_time - $start) / 90000;
		$out["Time"] = sprintf("%02d:%02d:%02d.%03d", $diffStart / 3600, ($diffStart % 3600) / 60, $diffStart % 60, ($diffStart*1000) % 1000);
		foreach ($data->splice_descriptors as $descriptor) {
			switch ($descriptor->segment_type_id) {
				case '02':
					$out['AdServer'] = $descriptor->segmentation_upid->code . ' ' . ($descriptor->segmentation_duration_flag ? $descriptor->segmentation_duration_text : 0);
					break;
				case '16':
					$out['Program'] .= ' +Start' . ' ' . ($descriptor->segmentation_duration_flag ? $descriptor->segmentation_duration_text : 0);
					break;
				case '17':
					$out['Program'] .= ' -End';
					break;
				case '34':
					$out['Break'] .= ' +Start' . ' ' . ($descriptor->segmentation_duration_flag ? $descriptor->segmentation_duration_text : 0);
					break;
				case '35':
					$out['Break'] .= ' -End';
					break;
				case '52':
					$out['Placement Opportunity'] .= ' +Start' . ' ' . ($descriptor->segmentation_duration_flag ? $descriptor->segmentation_duration_text : 0);
					break;
				case '53':
					$out['Placement Opportunity'] .= ' -End';
					break;
				case '48':
					$out['Advertisement'] .= ' +Start' . ' ' . ($descriptor->segmentation_duration_flag ? $descriptor->segmentation_duration_text : 0);
					break;
				case '49':
					$out['Advertisement'] = ' -End' . $out['Advertisement'];
					break;
			}
			//echo "\t";
			//echo $descriptor->segment_type_text;
		}
		echo sprintf($pattern, $out['Time'], $out['Program'], $out['AdServer'], $out['Break'], $out['Placement Opportunity'], $out['Advertisement']);
	}
}
echo "</pre>";

// Display Errors and JSON
echo "<h1>Messages details</h1>";
foreach ($done as $b64) { ?>
	<h3><?php echo $b64; ?></h3>
	<?php if (isset($error[$b64]) && !empty($error[$i])) {
		echo '<h4 class="error">'.$error[$b64].'</h4>';
	} ?>
	<?php if (isset($json[$b64]) && !empty($json[$b64])) { ?>
	<br/>
	<br/>
	JSON output :
	<pre>
	<?php echo json_encode(json_decode($json[$b64]), JSON_PRETTY_PRINT); ?>
	</pre>
<?php } ?>
<hr/>
<?php } ?>
<script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js"/></script>
<style>
.text { background: yellow; color: black; }
.id { background: orange; color: black; }
.type { background: lightgreen; color: black; }
.bold { font-weight: bold; }
.true { color: blue; }
.false { color: red; }
.error { color: red; font-size:2em; }
</style>
<script>
var context = document.querySelectorAll("pre");
var instance = new Mark(context);
instance.markRegExp(/[^\s]+_text.*/, {"element":"span","className":"text"});
instance.markRegExp(/[^\s]+segment_type_text.*/, {"element":"span","className":"type"});
instance.markRegExp(/[^\s]+segmentation_event_id_text.*/, {"element":"span","className":"id"});
instance.markRegExp(/"\(.*\) [^"]+"/,{"element":"span","className":"bold"});
instance.markRegExp(/true/,{"element":"span","className":"true"});
instance.markRegExp(/false/,{"element":"span","className":"false"});
</script>
</body>
</html>	

