<?php
require __DIR__ . '/SCTE35Parser.php';

$me = new SCTE35Parser();

// TimeSignal Example
//$base64 = '/DCAAAAMc3RIAP/wBQb/mZSU8ABqAhxDVUVJMACB4H/AAAAAAAAICDEyMzk2MzQAMQIDAixDVUVJAQAH+H/AAAAAAAAMGCElIhclNxVKCTcVABYeOxj7ERUWMRENDQEAAAIcQ1VFSTAAgeN/wAAAGLggCAgxMjQyODY0ADADA8N+pPM=';

//$base64 = '/DCWAAAMHO/YAP/wBQb/HGGQ0ACAAhxDVUVJEACBzX/AAAAAAAAICAAAAAAAAAAAEQEBAhRDVUVJIgAH6X/AAABHPkAAACIBAQIsQ1VFSQEAB+l/wAAAAAAADBghJSIXJTcVSgk3FQAWHjsYBiEUG0ERDQ0BAAACHENVRUkwAIHOf8AAAAQP0AgIMTYzSlAxMDUwAAPrds5u';

// Timesignal - break duration 61.960
// BUG! - avail with zero length
//$base64 = '/DCgAAALyooYAP/wBQb/NnnP4ACKAhxDVUVJMACB3H/AAAAAAAAICDE2OUpQNTEzMQADAhxDVUVJNAAH+H/AAABVE5AICDIwNDAAAAAANAAAAAACLENVRUkBAAf4f8AAAAAAAAwYISUiFyU3FUoJNxUAFh47GPsRFRYxEQ0NAQAAAhxDVUVJMACB3n/AAAAZXaAICDEyNDM5NzgAMAEDjkaQXw==';

// Timesignal - break duration 48.911
// BUG! - avail with zero-length
$base64 = '/DCgAAALyooYAP/wBQb/OleD8ACKAhxDVUVJMACBzn/AAAAAAAAICDE2M0pQMTA1MQADAhxDVUVJNAAH6X/AAABDKzAICDIwMjUAAAAANAAAAAACLENVRUkBAAfpf8AAAAAAAAwYISUiFyU3FUoJNxUAFh47GAYhFBtBEQ0NAQAAAhxDVUVJMACB0H/AAAAVPvAICDEyNTQxNjIAMAEDZWmHpw==';



// Splice Insert Example
//$base64 = '/DAlAAF3h3TAAP/wFAUAAAGvf+/+muBZcP4Aj6MAA05AQAAA6G2hfQ==';

echo $me->parseFromBase64($base64);
